### ISSUE TITLE
Feature Request for keep alive ping in non public.

### ISSUE THREAD

**Issue by AndyMcProducer** [jamulussoftware/jamulus#947] opened 2021-02-03 22:45 UTC
Hi, there doesn't seem to be an option to make a feature request and only to make a bug report.
This isn't really a bug as such, but when in non public mode the upnp port process is disabled
and no keep alive ping is done to keep the port open and routed.
Could this be adjusted so it still happens in non public more too?

Would reduce the need for complex port routing for some. Port routing is easy on some router/modems but some
are so backwards in going forwards. Mostly newer routers are more simple but some are silly not user friendly.

Thanks,
AndyMc...

**Comment by softins** [comment] 2021-02-04 15:39
I don't think this will work. Jamulus does not use UPNP for opening ports. That may be something worth exploring in the future.

What you are referring to isn't really a keep-alive ping, but rather the magic that happens when a server is registered as public with a Central Server. See https://github.com/softins/jamulus-web/issues/5#issuecomment-672231245 for my description of what happens.

When a server is private, i.e. not registered with a Central Server, there is no process to cause this automatic opening of NAT sessions, so it is necessary for the server operator to set up inbound port forwarding/enabling. It might be possible in the future to open inbound ports for a private server using UPNP, but that could well be a substantial item of development.

**Comment by WolfganP** [comment] 2021-02-04 17:40
If the issue is related to mapping UPNP ports programatically, you may try using http://miniupnp.free.fr/ 
If it works, you may craft an script for jamulus up & down, or include it in the pre-post execution of the service file.

**Comment by ann0see** [comment] 2021-02-04 18:02
@AndyMcProducer I think there's also the jamulusprivate list. Maybe this is something you could try? Just register the server with it and then unregister it after everybody joined.

I don't really see anything else we can do here...

See also #579 for upnp support.

**Comment by gene96817** [comment] 2021-02-04 19:20
An outbound UDP packet from the server on a private network will open the necessary NAT port. This should be enough for the private server to receive an inbound UDP packet on that port. Just sending a do-nothing ping to an address on the public network (e.g. the central server) should be enough.

**Comment by softins** [comment] 2021-02-04 20:45
> An outbound UDP packet from the server on a private network will open the necessary NAT port. This should be enough for the private server to receive an inbound UDP packet on that port. Just sending a do-nothing ping to an address on the public network (e.g. the central server) should be enough.

That won’t work, as the NAT session is associated with both local and remote addresses. So sending a UDP out to a specific address will only enable inbound traffic from that address, not from anywhere in general. That is why, when a client requests the server list from a Central Server, the Central Server tells each server in the list to send a message to the requesting client. That opens a session at each server allowing the client to ping it.

**Comment by gene96817** [comment] 2021-02-04 21:01
ah... I forgot that detail. That is why my server is in the DMZ. That way my server is the default destination for all inbound traffic. Of course, only one server can live in the DMZ. (This kind of DMZ is simple and common for consumer-grade routers.)

**Comment by AndyMcProducer** [comment] 2021-02-05 00:08
I was thinking more private being same as public except an extra trigger so the server knows not to list it. Doesn't really need any radical changes just an extra check when the server registers so it knows whether to list it or not.

**Comment by softins** [comment] 2021-02-05 10:58
> I was thinking more private being same as public except an extra trigger so the server knows not to list it. Doesn't really need any radical changes just an extra check when the server registers so it knows whether to list it or not.

I'm afraid that wouldn't help either. The private server opening a session to the Central Server (which then has been told not to list it) does not make it possible for some other client at a different address to connect back in to the private server.

I think that proper UPNP support is actually the way to go, but that's definitely a non-trivial addition and would take time. I intend to experiment with it. Thanks to other commenters above for the links.

**Comment by ann0see** [comment] 2021-02-05 22:47
Since I think the outcome of this is upnp support, I'll close this and discussion should be continued in the other issue. Just reopen it if you're not ok with this.

**Closed by ann0see** 2021-02-05 22:47 UTC
Labels: improvement
