### ISSUE TITLE
Clarify ASIO SDK usage

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2417] opened 2022-02-20 21:27 UTC
It seems to be non-obvious how the ASIO SDK and its license integrates with Jamulus. We should do everything to make the situation more clear.

- [x] Add a clause on the Windows ASIO client download page saying "Please note that you are not permitted to redistribute this binary without acquiring a [licence agreement from Steinberg](https://www.steinberg.net/developers/)" (and in the About box)
- [x] Make a Windows server download using "nosound" which doesn't touch ASIO SDK
- [x] Verify that JACK Windows builds don't touch ASIO SDK #2443
- [x] Check/update ASIO mentions regarding license requirements in
  - [x] Installer Startup/Splash-screen ("ASIO" + copyrights notice - see 3.b in their Terms, logo is optional)
  - [x] About dialog ("ASIO" + copyrights notice)
  - [x] [README.md](https://github.com/jamulussoftware/jamulus#acknowledgements) (copyrights notice only)
  - [x] Website ("ASIO" + copyrights notice, logo is optional). 
- [ ] Sign the agreement and send it to Steinberg to cover jamulus.io's distribution of ASIO-enabled Windows binaries (we can't cover other usages, sadly)
  - [x] Who from the team would be available to do that? @gilgongo + @pljones for deeper technical stuff
- [x] Agree approach re. system GPL library exception vs additional terms notice 
- [x] Document that users who self-compile and distribute the result should check this for themselves ([README.md](https://github.com/jamulussoftware/jamulus#acknowledgements) as well?)
- [x] Add pointers to the code to be careful about this topic, i.e. *"never copy from ASIO SDK as it makes the situation more complicated"*
  - [x] [windows/deploy_windows.ps1](https://github.com/jamulussoftware/jamulus/blob/master/windows/deploy_windows.ps1#L8) #2443
  - [x] windows/sound.h #2443

References:
See PDF in the [SDK zip](https://download.steinberg.net/sdk_downloads/asiosdk_2.3.3_2019-06-14.zip).

I'm currently don't plan to work on this myself, but I do think that we should move this forward for the next release and have added it to 3.9.0 therefore.

**Comment by gilgongo** [comment] 2022-02-21 15:22
The approved wording for the copyright statement is: ”ASIO is a trademark and software of Steinberg Media Technologies GmbH”

**Comment by gilgongo** [comment] 2022-02-23 14:31
I think the _least contentious_ option here is to give anyone who receives the Jamulus source an additional permission under GNU GPL v3 section 7 as follows:

_Parts of this program that relate to hosting ASIO device drivers under Microsoft Windows are covered by the terms of the Steinberg ASIO SDK Licensing Agreement. The licensors of this Program grant you additional permission to convey the resulting work, provided you agree to Steinberg’s terms in writing. For further information, see https://www.steinberg.net/developers/_

This hinges on the assumption that the Steinberg agreement does not contain any non-permissive additional terms considered "further restrictions" within the meaning of section 10 of the GPL v3. 

I've got notes on the thinking (and other options) around this if [anyone wants to read that here](https://docs.google.com/document/d/1yHx4WwusaicnAHisi0_AvxRDGJgs4Ogl71iXOq3sVBc/edit?usp=sharing).

**Comment by gilgongo** [comment] 2022-02-24 16:20
@hoffie I've amended the text on this to be more specific about what's needed.  

As far as I can see, we should take the "additional permission" route and not treat ASIO as a system library (see my comment above). 

If that's agreed then I can sign the Steinberg agreement unless anyone else wants to (what's the name of the Jamulus "organisation" now BTW?), and we can get on with displaying the copyrights notices as I've detailed above meanwhile.

**Comment by hoffie** [comment] 2022-02-24 22:56
Thanks for working that out!

> I think the least problematic option here is to give anyone who receives the Jamulus source an additional permission under GNU GPL v3 section 7 as follows:

I think we would have to choose the GPLv2 version of this which also exists at https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs. We should keep any modifications to that text to the bare minimum -- they likely did think a lot about the proper wording.

> As far as I can see, we should take the "additional permission" route and not treat ASIO as a system library (see my comment above).

That'd effectively be a license change though. That would mean that we would need to get approval by all relevant contributors, right? Luckily, it seems like it is sufficient to do that for the parts which interact with the library (ASIO), so that would only be `windows/sound.{h,cpp}`. Based on (emphasis mine):

> In either case, you should put this text in **each file** to which you are granting this permission.

```
$ for x in windows/*.cpp windows/*.h; do git blame $x | sed -rne 's/.*\((\S+ ?\S+)  .*/\1/p' ; done | sort -u
ann0see
Martin Passing
Noam Postavsky
Stefan Weil
Tony Mountifield
Volker Fischer
```

That'd be really good as it seems absolutely realistic to reach those few people. Some exceptions:
- Stefan Weil did comment changes only, so one could argue that it is not linking-relevant
- Martin Passing is listed due to the clang changes. I'd argue that the execution of `clang-format` is not copyrightable.
That way we would be down to 4 people, which should work!

https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs
> But if you want to use parts of other GPL-covered programs by other authors in your code, you cannot authorize the exception for them. You have to get the approval of the copyright holders of those programs.

I guess this would also only apply to the relevant files (`windows/`), right?

**Comment by gilgongo** [comment] 2022-02-24 23:24
@hoffie Good point about the GPLv2 version... 

> That'd effectively be a license change though.

Not sure I understand why that would be. Can you explain?

**Comment by gilgongo** [comment] 2022-02-24 23:24
@hoffie Good point about the GPLv2 version... 

> That'd effectively be a license change though.

Not sure I understand why that would be. Can you explain?

**Comment by hoffie** [comment] 2022-02-24 23:31
Basically this:

[> Only the copyright holders for the program can legally release their software under these terms. ](https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs)

As we do not assign copyright, every author with major contributions must be considered to own (partial) copyright as far as I understand. Volker could have done it alone. Now, it can only be done when all relevant authors agree to that change.

**Comment by gilgongo** [comment] 2022-02-25 09:53
Re. the GPLv2 permission wording though, the GPLv3 one feels safer because it doesn't seem to let distributors remove the notice on modified versions as far as I can tell (If we wanted to stick to the wording in the gnu.org FAQ, and not go off piste as I did above).

At least in so far as we're saying we're releasing under the "GPLv2 or above", we can align this with GPLv3, no?

**Comment by gilgongo** [comment] 2022-02-26 22:18
> Since I‘m not a fan of copyleft I‘ll happily hand my copyright (which is certainly arguable since my changes were minor) to Volker Fischer or Tony Mountfield (so you can remove me from the list).

While I guess getting permission can't hurt, I'm slightly confused as to why we need to (the GPL FAQ says you only need permission, "if you want to use parts of **other GPL-covered programs** by other authors in your code"). But I suppose it's not a big deal.

**Comment by hoffie** [comment] 2022-02-26 22:29
> At least in so far as we're saying we're releasing under the "GPLv2 or above", we can align this with GPLv3, no?

I no longer claim to have a full understanding of this by now, but I'd fear that this might only "solve" it for GPLv3 and not for GPLv2 which people would (and must) still be allowed to use. Based on that I'd use the GPLv2 suggestion.

> I'm slightly confused as to why we need to (the GPL FAQ says you only need permission, "if you want to use parts of other GPL-covered programs by other authors in your code").

I find that paragraph confusing as well. The first part talks about single-author GPL programs (that's what I paraphrased), the last part talks about "other GPL-covered programs" (that's what you paraphrased). I don't see an explicit mention of "GPL programs by multiple" authors, but I still read the paragraph as: All authors must agree.

BTW, some of the initial TODO items in this Issue are now marked as obsolete. I agree with some of those (we don't have to document our ASIO-is-a-platform-library as we don't plan to go this route anymore), but regarding the other items I'm not sure. Wouldn't all users who self-compile and distribute still need to sign the agreement? If so, shouldn't we point them to it?

**Comment by gilgongo** [comment] 2022-02-28 22:48
OK so as further discussed on Discord just now, if we assume that the only issue is the distribution of the Windows client binary which is the object of Steinberg's terms, then we don't have to worry about the source (which contains none of their code). Ergo, we don't need an addendum to the GPL. This assumes that because Steinberg don't mention source or binaries, we can interpret their rights granted on "an application that can host ASIO device drivers" as applying only to the binary. 

I've updated the ticket with the actions we need to take, and will mark the above discussion items as "resolved".

**Comment by pljones** [comment] 2022-03-01 21:39
> I assume it's just "Jamulus"

Given the Github account is "jamulussoftware", I use "Jamulus Software" in full - that way it more clearly covers every usage under that account, rather than perhaps jamulussoftware/jamulus.

> "technical representative"

Well, you know the set of qualifying volunteers.  I'm happy to have my name there.  Does it need my signature, too?

(Maybe photo your signature, cut-n-paste in an appropriate editor, print to PDF - no paper involved...)

**Comment by hoffie** [comment] 2022-03-02 19:55
> Make a Windows server download using "nosound" which doesn't touch ASIO SDK

I'm no longer convinced that we should have this. I think there's a risk of confusing users ("why doesn't this work as a client with audio?") and it's yet another build target with questionable benefit. Do we really need it?

**Comment by pljones** [comment] 2022-03-03 07:30
> > Make a Windows server download using "nosound" which doesn't touch ASIO SDK
> 
> I'm no longer convinced that we should have this. I think there's a risk of confusing users ("why doesn't this work as a client with audio?") and it's yet another build target with questionable benefit. Do we really need it?

We do it for Linux, seemingly without problems.  We create two apps for MacOS, seemingly without problems.  Why shouldn't Windows uses also have two?

**Comment by gilgongo** [comment] 2022-03-03 07:53
> Technically (in licensing terms), no, there's little benefit.

I suppose in the seemingly very unlikely event we had to take the Windows client closed source (ie if Steinberg said their terms covered the source after all) then I guess we might have to? But the practicalities of maintaining a private repo for that seem to make that a non-starter. We'd need funding, for one thing.

**Comment by hoffie** [comment] 2022-03-03 22:43
> Technically (in licensing terms), no, there's little benefit.

Hrm, maybe track it as a separate task then?

> I suppose in the seemingly very unlikely event we had to take the Windows client closed source

I don't think this is possible at all.

**Comment by gilgongo** [comment] 2022-03-16 10:06
BTW I've updated the requirements to make the logo not needed. For the installer and About screen it says in 3.b  'the Licensee shall display “ASIO” and Steinberg’s copyrights notice **or** the ASIO compatible Logo and Steinberg’s copyrights notice' and for the website, '“ASIO” and Steinberg’s copyrights notice **or** the ASIO compatible Logo and Steinberg’s copyrights notice on any product website'. 

At first I thought "ASIO" meant the logo, but it seems not so that's good.

**Comment by hoffie** [comment] 2022-04-06 19:23
@henkdegroot I think you said you wanted to tackle parts of the open TODOs. Is this accurate? If so, which?

**Comment by henkdegroot** [comment] 2022-04-06 19:44
@hoffie, that is correct. Offered to update the windows installer etc. to cover the requirements. But then I noticed a comment that it might not be needed after all.

**Comment by gilgongo** [comment] 2022-04-06 20:28
I think all we need in the installer is the rights notice, not the logo. So I think the words "ASIO compatible. ASIO is a trademark and software of Steinberg Media Technologies GmbH”

**Comment by henkdegroot** [comment] 2022-04-09 12:59
> So I think the words "ASIO compatible. ASIO is a trademark and software of Steinberg Media Technologies GmbH”

So reaching the next question, in which screen (installer) should we show this information?
First screen is a Welcome message.
![image](https://user-images.githubusercontent.com/13550012/162574665-bbf150a4-9b5d-41fd-a032-14b57841f2df.png)

Second screen, is ASIO (or JACK) specific and only displayed when there is no driver installed. This can be updated to always show for ASIO and have the corresponding text included.
![image](https://user-images.githubusercontent.com/13550012/162574676-2581c7b7-9a0f-4488-b6df-51ab2cb3600d.png)

Third screen, GPL Licence Agreement. I would say this needs to be kept GPL specific.
![image](https://user-images.githubusercontent.com/13550012/162574702-04332088-635d-44a6-ba0c-dc14fc35a47c.png)

Fourth screen, install location. This does not seem to be the appropriate page.
![image](https://user-images.githubusercontent.com/13550012/162574724-3b162a3f-baaf-4838-8c7d-745ba8787c6f.png)

Final screen, completing page. This could have the text included.
![image](https://user-images.githubusercontent.com/13550012/162574748-9774579a-c349-44fb-b919-74b24ad2b473.png)

Alternative, a new dialog could be introduce specific for ASIO licence information. If this is selected, should it have an "I agree" button or would a simple "Next" be sufficient?

The "About dialog" is referenced as well. Would this be a separate item in the menu (like what has been done for Qt) or do we just add some information to the About or Libraries tab?

Thinking the "command line" help/version option should also be updated. Correct?

Translatable or not? We had some discussions in the past about licence text and it's translation. Does this text require translation?

Sorry for all these questions, too many options to make a good educated guess.

**Comment by pgScorpio** [comment] 2022-04-09 21:02
I would say use the second ASIO specific screen and maybe include a  "(!) No ASIO drivers found!" or "(v) n ASIO driver(s) found." message.

(!) == Red exclamation mark icon,
(v) == Green checkmark icon.

**Comment by gilgongo** [comment] 2022-04-09 21:52
@henkdegroot 

I'd be inclined to just put it on the first screen. Can we put it in the blue area at the bottom so as to get it out of the way of the instructions? There is no "I agree" required by Steinberg, BTW.

The "About dialog" refers to what you get in the app, not the installer.

The command line is not mentioned in the Steinberg terms I don't think, but I guess if we wanted to be nice we'd put it in there (and therefore also in that damn man page...)

The translation issue is interesting. I suppose it makes sense to have it translatable although Steinberg don't mention that. For all I know there may be a "wrong" way of translating it. But maybe have it as a translatable string at least?

@pgScorpio OK, but that's a separate issue.

**Comment by pgScorpio** [comment] 2022-04-09 23:07
@gilgongo 

> @pgScorpio OK, but that's a separate issue.

What is a separate issue ?

I suggest to use the ASIO specific screen that normally is only showed when no ASIO driver is installed. So when we always show this screen to show the ASIO disclaimer we should, maybe, have an indication whether an ASIO driver is installed or not.

**Comment by gilgongo** [comment] 2022-04-10 06:46
@pgScorpio Sorry, I meant that if we are changing the way the messaging works or adding wording/layout changes then that's a separate thing we need to look at I think unless Henk wants to also do that. 

The reason why I say put it on the first screen is that would having it on the second ASIO screen confuse things for users of the JACK version?

**Comment by henkdegroot** [comment] 2022-04-10 09:59
> The reason why I say put it on the first screen is that would having it on the second ASIO screen confuse things for users of the JACK version?

The ASIO screen does not apply to the JACK version. You get a JACK screen, when JACK is not found.

I like the suggestion of adding it to the ASIO screen with the extra icon to indicate error/green mark and might be easier in case  we decide to move to a different audio integration.

@gilgongo, if added to the help/version output...then it should only be for the Windows build with ASIO. So no update to the man page I would say.

I also assume the disclaimer in the About screen should also only be there when actually running a build with ASIO support. Do you see it the same?

**Comment by gilgongo** [comment] 2022-04-10 10:47
> The ASIO screen does not apply to the JACK version. You get a JACK screen, when JACK is not found.

OK. Be that as it may, while the Steinberg agreement doesn't talk explicitly about installers, it does talk a lot about "Startup-/Splash-screens", which is why I think we may be safest putting on the first screen in the installer, since that's effectively a "startup" screen, even though you only see it once. And yes, I guess the rights statements need only appear in the ASIO version of the installer.

I forgot that the man page is only for Linux, so agree that's not relevant.

As to the extra icons - if you want to add those in then don't let me stop you if it's easy enough to do as part of adding the ASIO rights text.

**Comment by henkdegroot** [comment] 2022-04-10 11:08
@gilgongo, well if we add it to the first page, then the ASIO page does not require changes (at least for now).

Following text is taken from the Steinberg agreement:

if an About Box or a Startup-/Splash-screen exists that includes any reference to any third party or third party’s right, “ASIO” and Steinberg’s copyrights notice or the ASIO compatible Logo and Steinberg’s copyrights notice in every About Box **or** every Startup-/Splash-screen.

They also have the **or** in bold and even underlined. 
I believe the dialogs display in the installer are NOT the so cold startup-/splash-screens. To my knowledge a startup-/splash-screen appears when you start the software, which is something we don't have/use.
For reference, the installer dialogs log do not mentioned Qt as well, so we don't have any third part right displayed in that.

Also the highlight **or** makes me wonder if we should just about the About box and just include it in the libraries tab.

What do you thing?

**Comment by gilgongo** [comment] 2022-04-10 11:33
Yes, we could interpret what they say as, "You need to add our rights statement in any startup screen, but that doesn't include your installer." But I feel that's not in the spirit of their agreement 🙂

**Comment by henkdegroot** [comment] 2022-04-10 19:34
In the spirit of their agreements it is :) Will do a PR later this week (probable next weekend) with this added to the first screen and About dialog.

**Comment by pgScorpio** [comment] 2022-04-11 13:19
Why not simply just add an About "ASIO" to help for the ASIO builds, like we also have an "About Qt". Wouldn't that be much simpler ?
Even adding a splash screen (first thing started from main) would be simpler than adding conditional code al over the place... (And a splash screen also would make Jamulus seem more responsive at startup.)

**Comment by gilgongo** [comment] 2022-04-11 13:43
> Why not simply just add an About "ASIO" to help for the ASIO builds, like we also have an "About Qt"

It's debatable of course, but I don't think that would comply with Steinberg's wish that we put their rights statement on _our_ about screen. Maybe I'm just being over-cautious.

> Even adding a splash screen (first thing started from main) would be simpler than adding conditional code al over the place... 

I can't comment on code complexity, but if we had a splash screen for the app, we'd still need an About screen with the Steinberg right statement on it.

**Comment by henkdegroot** [comment] 2022-04-11 15:20
> "About Qt". Wouldn't that be much simpler ?

I don't think it will matter. A conditionally inculded menu item or conditionally included text.

**Comment by pgScorpio** [comment] 2022-04-11 17:07
> I can't comment on code complexity, but if we had a splash screen for the app, we'd still need an About screen with the Steinberg right statement on it.

AFAIK the Steinberg documents says "About Box **or** every Startup-/Splash-screen." so not **and**

**Comment by ann0see** [comment] 2022-04-11 19:06
We don't have a Startup/Splash screen, so I'd just go with a conditional logo in About. That makes the difference between JACK and ASIO enabled builds also easier.

**Comment by henkdegroot** [comment] 2022-04-11 20:36
I was thinking about the following for the About and version text:
![about-libraries](https://user-images.githubusercontent.com/13550012/162827209-bf05bfc8-93dd-420c-a709-ee7cea22c119.png)

![command-line-version](https://user-images.githubusercontent.com/13550012/162827226-93bd651f-53c8-4d9c-820a-14b9789c3cd2.png)

Not sure how "easy" the installer Welcome page can be modified. The blue section (left part) is a relative small size image, adding text is not really nice. Perhaps I can add the ASIO logo here and in the "text" part of the dialog, add the disclaimer at the bottom...but still investigating if that can be done.

**Comment by ann0see** [comment] 2022-04-11 20:44
Yes. But wouldn't we need a logo there?

... I still don't get why we need to add anything to the installer. The app would be enough, I hope...

**Comment by gilgongo** [comment] 2022-04-11 20:59
@ann0see it's somewhere in the discussion above, but the logo appears optional (if you look at their guidelines). As to the installer:  https://github.com/jamulussoftware/jamulus/issues/2417#issuecomment-1094251324 (basically, they are extremely vague about what they want, but I'd rather we do our best and not be unnecessarily picky)

**Comment by gilgongo** [comment] 2022-04-11 21:02
@henkdegroot if using the logo is easier, we can I think use that (they supply a jpg) instead of the text since the image has both the logo and the text:

[Steinberg ASIO Logo Artwork.zip](https://github.com/jamulussoftware/jamulus/files/8467704/Steinberg.ASIO.Logo.Artwork.zip)

**Comment by gilgongo** [comment] 2022-04-11 21:15
BTW I may as well add the rights statement to README.md while we're at it.

**Comment by hoffie** [comment] 2022-04-12 22:14
@henkdegroot 
> I was thinking about the following for the About and version text:

I like that very much. We should give credit where credit is due (and even more so when required by a license... ;)). It's also appropriate to list ASIO SDK as third item after Qt and opus, in my opinion. We must comply with the license demands, but we should not make ASIO stand out too much. Also, it would obviously be best if all of this would be restricted to Windows ASIO builds.

As for the installer, I think we should add the text as well as we do display other license text, too. The existing combined "license agreement" page seems appropriate (this page may seem like "it's just the GPL", but it isn't -- it contains licenses of other bundled libraries. Maybe this should somehow be made more obvious by adding a header or something).

I don't think we should add splash screens or additional installer pages as part of this issue.

**Comment by henkdegroot** [comment] 2022-04-13 15:18
> I think we should add the text as well as we do display other license text, too.

You are correct, the license text is loading the COPYING file from the root folder. I do not see an easy option to combine two files and if that would be possible, it would add the ASIO text at the end of the file. Would it be okay to have a COPYING_ASIO which contains the same text as the existing COPYING file and also include the required ASIO text just after the OPUS details.

The installer can then load the file depending on JACK or ASIO. 
And the first screen of the installer can then include the ASIO logo.

**Comment by ann0see** [comment] 2022-04-13 16:51
> The installer can then load the file depending on JACK or ASIO.

Better copy the COPYING_ASIO file to the installer via deploy_windows.ps1 (that's what I'd do

**Comment by henkdegroot** [comment] 2022-04-13 17:37
> installer via deploy_windows.ps1

Not sure if that is a good idea, think it would be best to keep "installer" related logic in the installer nsis and that is already capable of handling the jack/asio condition. 

My concern is more about have two almost the same "COPYING" files in the root.

**Comment by ann0see** [comment] 2022-04-13 17:49
I mean you could also just echo (append) the ASIO text to the COPYING file programatically?

**Comment by henkdegroot** [comment] 2022-04-15 19:23
I did not realize that the logo also includes the rights statement and therefore believe we do not have to add the steinberg text to it after all.
Here is a sample of the start and finish page of the installer, they both use the same bitmap image:
![installer-welcome](https://user-images.githubusercontent.com/13550012/163623323-c7f5aca0-6a0e-4176-ad7f-e607c45b39c8.png)
![installer-finish](https://user-images.githubusercontent.com/13550012/163623340-226b2cde-0fad-4156-b545-2128a9a42b15.png)

This will only be used when the installer is created for the ASIO version.

Let me know what you think about this.

**Comment by ann0see** [comment] 2022-04-15 21:17
Maybe – however the contrast looks a bit strange. 

@mulyaj is the graphical expert, so he should judge

**Comment by henkdegroot** [comment] 2022-04-16 05:36
I have used the eps format logo, which does not include a background for the text below the logo while the other logo formats do have a white background. Perhaps we need to use a white background for the text below the logo as well?

**Comment by ann0see** [comment] 2022-04-16 06:08
Yes. Maybe try this

**Comment by henkdegroot** [comment] 2022-04-16 08:49
Image with white background for the text:

![installer-welcome-white](https://user-images.githubusercontent.com/13550012/163668103-9eaada57-3e57-4ed8-9aff-2e4831993181.png)

I cannot get the text readable...due to the very limited image size in the installer dialog (164 pixels width). 

Unless you want/accept the logo to be bigger like this:

![installer-welcome-white-big](https://user-images.githubusercontent.com/13550012/163668663-da2ab37d-5ea8-4428-b1ff-bc1d131a8c61.png)

**Comment by ann0see** [comment] 2022-04-16 08:54
The second image looks a bit bloated, so I'd go with the first :-)

**Comment by gilgongo** [comment] 2022-04-16 09:38
Or cut off the bottom of the image and use plain text if that makes it look less bloated?

**Comment by henkdegroot** [comment] 2022-04-16 14:36
Using plain text is even worse as it is very small text. I'll check if I can get it any better. 

Op 16 apr. 2022 11:38, om 11:38, Jonathan ***@***.***> schreef:

**Comment by hoffie** [comment] 2022-04-16 15:10
As it seems hard to find a good way to show the logo, maybe let's step back once again: Do we actually need to show the logo? Based on the comments above, it seems like this path was chosen because it seemed simpler, not because it was a strict requirement.
I still find it strange to show ASIO notices more prominently than attributions for other, more foundational libs such as Qt and Opus.

**Comment by pgScorpio** [comment] 2022-04-16 17:06
> I still find it strange to show ASIO notices more prominently than attributions for other, more foundational libs such as Qt and Opus.

I totally agree on that.

And it also amazes me there is so much discussion here on the ASIO disclaimers. I know Steinberg's licensing documentation is not very clear, but is that a reason to overdo it?
Looking at other ASIO software and products, like ASIO4ALL, ASIO Link Pro, Behringer and Focusrite drivers and interfaces I don't see any Steinberg Logo's or disclaimers in the software or on the product at all! Some have just a short disclaimer in the documentation, but even that is not always the case.

**Comment by gilgongo** [comment] 2022-04-16 17:36
>And it also amazes me there is so much discussion here on the ASIO disclaimers.

The problem is that the wording of the Steinberg licence terms is pretty hard to work out in the detail of where they want you to show their rights statement. But **the use of the logo appears to be optional** (as I've staged _several_ times but after a while nobody reads these threads...). I didn't put the logo on the website, although it could be said they say we need it there. Whatver.

As to the fact that other people seems to be non-compliant, my view is that  they can take that risk if they want to (and they may in some cases be able to carry on without ASIO anyway). But I don't think we should take it unless we're prepared to migrate to an alternative.

**Comment by gilgongo** [comment] 2022-04-16 17:40
> Do we actually need to show the logo? 

No. It was only if we thought it might look better. 

> I still find it strange to show ASIO notices more prominently than attributions for other, more foundational libs such as Qt and Opus.

We don't have a T&Cs document to comply with in those cases though, do we?

**Comment by hoffie** [comment] 2022-04-16 18:11
> We don't have a T&Cs document to comply with in those cases though, do we? (Jeez, we better not do...!)

Well, the licenses of Opus (BSD) and Qt (LGPL) itself demand proper attribution and documentation, of course:
- Opus: [*Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution*](https://opus-codec.org/license/)
- Qt: Among others, [*For a Combined Work that displays copyright notices during execution, include the copyright notice for the Library among these notices, as well as a reference directing the user to the copies of the GNU GPL and this license document.*](https://doc.qt.io/qt-5/lgpl.html)

If anyone sees open TODOs in that regard (I don't), I suggest opening separate issues.

I mainly mentioned the other libs for context: While the goal of this issue is compliance with the ASIO terms, we should do that in a way which is in line with how we do it for the more fundamental bases of Jamulus.

**Comment by gilgongo** [comment] 2022-04-16 18:22
We could add those along with the ASIO logo in @henkdegroot installer screen work. Might make it look a bit less random.

**Comment by henkdegroot** [comment] 2022-04-17 08:42
@hoffie, the reason for using the logo is because the Welcome page (in the installer) allows changing the bitmap image being displayed. The text in the welcome page dialog isn't really easy to modify in nsis (the text displayed comes from NSIS).

I am also not a big fan of the larger ASIO logo on this and would prefer to use the smaller version. Even with the text not being fully readable, it at least shows the logo.

To be honest the "installer" is not technically a splash/startup screen of the application so would not be required to update.
Add the ASIO specific disclaimer to the text displayed in the license dialog could be the alternative.

**Comment by henkdegroot** [comment] 2022-04-17 08:45
> Even cakewalk SONAR 8 just has two lines of text in the "Trademarks" section of the "about SONAR"

Interesting to see this....Steinberg explicitly mentions the logo with green and red arrow is not allowed to be used. Also noticed that Cakewalk by BandLab is using the same incorrect log and text as in SONAR and as mentioned because others a non-complaint, that does not mean we should not be.

**Comment by henkdegroot** [comment] 2022-04-17 11:25
> The text in the welcome page dialog isn't really easy to modify in nsis (the text displayed comes from NSIS).

Actually, I think I found a method to add text. Will do some testing tomorrow.

**Comment by henkdegroot** [comment] 2022-04-18 12:44
Here a sample with the ASIO text added to the dialog:

![installer-welcome-text](https://user-images.githubusercontent.com/13550012/163810172-694ec7e0-5644-4c0c-b49d-fc763605eb2e.png)

Would that be okay?

**Comment by pgScorpio** [comment] 2022-04-18 12:57
> Would that be okay?

Well I looks good to me, but inexperienced users might be confused. "What is ASIO, and what has this to do with Jamulus?"

So we could add something like:
```
This version of Jamulus uses ASIO audio drivers.
ASIO is a trademark and software of Steinberg Media
Technologies GmbH
```

**Comment by gilgongo** [comment] 2022-04-18 14:46
The terms say "the Licensee shall display 'ASIO' and Steinberg’s copyrights notice or the ASIO compatible Logo and Steinberg’s copyrights notice". What they mean by "shall display ASIO" is hard to say if it's not the logo, but I guess @pgScorpio interpretation may well be fine.

(For the website, I just had "ASIO®  - ASIO is a trademark and software of Steinberg Media Technologies GmbH")

**Comment by henkdegroot** [comment] 2022-04-18 15:12
> What is ASIO, and what has this to do with Jamulus?

And what will they do? Guess they just click Next :) 

Also note that the ASIO text will not be a translatable text, as Steinberg states that is what their statement should be.

Getting back to a "logo", what about adding the ASIO Compatible logo (just the top part, without the text) in the bottom right corner of the bitmap? (So that is positioned just left to the ASIO text)

**Comment by pljones** [comment] 2022-05-22 16:55
#2605 is done now, so can someone update here on what's left?  Thanks.

**Comment by gilgongo** [comment] 2022-05-22 17:49
I think think the checklist is up to date (assuming we're OK with [the installer screen](https://github.com/jamulussoftware/jamulus/issues/2417#issuecomment-1104092437)

**Comment by hoffie** [comment] 2022-05-22 18:41
> #2605 is done ready, pending approve and merge.

Just approved and merged that. That also covers the About screen in my opinion, so I've marked that task as done as well.

So, the only mandatory task before signing/sending the agreement would be this, I think?
*Document that users who self-compile and distribute the result should check this for themselves ([README.md](https://github.com/jamulussoftware/jamulus#acknowledgements) as well?)*

**Comment by gilgongo** [comment] 2022-05-28 18:12
On the "self-compile and distribute" thing, we need to say something like "If you intend to distribute Jamulus for Windows yourself, you will need to get a licence to do so from Steinberg and comply with its terms on displaying their copyright notice" - is that right?

**Comment by hoffie** [comment] 2022-05-28 19:59
> we need to say something like "If you intend to distribute Jamulus for Windows yourself, you will need to get a licence to do so from Steinberg and comply with its terms on displaying their copyright notice" - is that right?

Yes, I'd say so. We could try to outsource any interpretation what this means even more like this:
*"If you intend to distribute Jamulus for Windows (ASIO) yourself, you will need to ensure that you are in compliance with Steinberg's licence terms as described in the PDF in their ASIO SDK zip file."*

**Comment by henkdegroot** [comment] 2022-05-29 06:04
> PDF in their ASIO SDK zip

Not sure if it should be mentioned like this, as we don't distribute this zip file with the release.

**Comment by pljones** [comment] 2022-05-29 11:57
It should be the title of the document and something like "available in the ASIO SDK from Steinberg".

**Comment by gilgongo** [comment] 2022-06-03 10:34
Might be it better to direct people to their developer page? That way we don't need to worry about updates to document names and stuff (and maybe one day they might even change to be GNU friendly). So:

"If you intend to distribute Jamulus for Windows (ASIO) yourself, please ensure that you are in compliance with Steinberg's licence terms: https://www.steinberg.net/developers"

**Comment by gilgongo** [comment] 2022-06-03 10:59
We are now in compliance with what Steinberg want, so all that remains is to sign their agreement. We can presumably produce the `nosound` non-ASIO Windows server later as that's more about us than them.

I'll ping the relevant people for their signatures offline.

**Comment by ann0see** [comment] 2022-06-14 21:06
Ok. The nosound build could also just be the JACK build, so I‘d say for now that’s the way to go without ASIO.

**Comment by pljones** [comment] 2022-06-18 10:37
@gilgongo Any update on the admin side?

**Comment by ann0see** [comment] 2022-06-18 20:21
Ah yes, and please do not hide the comments on this issue to make them visible without the need of being logged in.

**Comment by pljones** [comment] 2022-06-25 13:26
Just to add:

> * [ ] Make a Windows server download using "nosound" which doesn't touch ASIO SDK

This is now called "serveronly" to make it clearer what it's for.  The "no-ASIO" Windows _client_ is the JACK one, as @ann0see says.  I think this action can be marked done.

**Comment by pljones** [comment] 2022-06-25 13:55
@hoffie 
> * [ ] Sign the agreement and send it to Steinberg to cover jamulus.io's distribution of ASIO-enabled Windows binaries (we can't cover other usages, sadly) 

From what I saw, I'd done my bit -- is there anything left from our side to do here?

**Comment by pljones** [comment] 2022-06-30 17:05
Looks like we're stuck on this until we here from @gilgongo again.

**Comment by gilgongo** [comment] 2022-07-02 09:17
Oops sorry - I was just thinking that we can only sign and send when we've released the changes.

**Comment by hoffie** [comment] 2022-07-02 09:22
Ah, good point. If they check carefully (or at all), it might make sense to do it that way.
Maybe close this one as done as part of 3.9.0 and open a new issue for sending the agreement post-3.9.0?

**Comment by gilgongo** [comment] 2022-07-02 09:27
OK let's do that then - closing this as done and I'll prep an issue.

**Closed by gilgongo** 2022-07-02 09:27 UTC

**Comment by mirh** [comment] 2025-01-31 00:57
I'll have you know gentlemen, that tentative solutions kinda exist.
https://github.com/s13n/cwASIO
https://github.com/rleathart/SimpleASIO
