### ISSUE TITLE
Qt6: Investigate UI glitches on Windows 11 and Mac

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2363] opened 2022-02-08 21:17 UTC
@ann0see noticed UI glitches in the Qt6 preview builds in https://github.com/jamulussoftware/jamulus/issues/2299#issuecomment-1032428424_

1. Strange lines:
  On Windows 11 there seem to be strange lines on the GUI which disappear on click. It looks as if one marked some invisible button:
  
  ![image](https://user-images.githubusercontent.com/20726856/152964776-48b52388-1988-418b-94ff-9c013cf670b0.png)
  
  ![image](https://user-images.githubusercontent.com/20726856/152964924-d7dfc8b0-1571-414d-b7c4-6643a9d07123.png)

2. Another issue
  ![image](https://user-images.githubusercontent.com/20726856/152965109-5928b041-9a62-4320-b110-edaa7c5e4310.png)

3. A macOS issue (I doubt it's new): 
  ![halleffekt](https://user-images.githubusercontent.com/20726856/152971953-0c164aa9-fba5-4435-b488-35084e7a014d.png)
  The lines seem to be at the wrong position. On macOS I think Qt6 is an improvement (at least UI wise)

**Comment by hoffie** [comment] 2022-02-08 21:23
@ann0see Thanks for the tests.

1. Some questions
  a. Does this only happen with the fancy skin?
  b. Is this reproducible in your (@ann0see) machine / has anyone else observed this (@henkdegroot and @dcorson-ticino-com  test runs, IIRC)?
  c. Does this happen with the Qt6 build on Windows 10?
  d. Does this happen with a Qt5 master build on Windows 11?

2. I have a hard time figuring out what the problem is as multiple things look strange at first sight. Is it the overlapping of the "Trennen" button? Or the high ping? Or the scroll bar?

3. Are you saying this is broken in the official Qt5-based builds as well? Then we should probably remove this here and make it a separate issue? I don't think I've seen that reported so far.

**Comment by henkdegroot** [comment] 2022-02-09 07:08
Not seeing these glitches on my Win11 system. Also tested if display scaling could cause this, but 100, 125 and 150% all looking good to me. Even checked with german language in case it was caused by text length differences.

**Comment by ann0see** [comment] 2022-02-09 09:27
1. This can be reproduced. Qt5 doesn’t provoke these errors. I can’t test on Windows 10. I did not try the compact/normal skin yet. 
2. I didn’t even notice the high ping. Probably it‘s  unrelated. I mainly focused on the white bar under the disconnect button.
3. I tested the Qt5 build too and it’s a bit different; however I need to re-test it.

**Comment by henkdegroot** [comment] 2022-02-09 18:38
I have tested the Qt6 build on a second win11 system and no issue with the display of the GUI.
However I did notice my selected (saved) country/region changed. Previous version (with Qt5) installed, I had selected Netherlands. Now with Qt6 my country is Mayotte. Not sure which issue is best to report this at.

**Comment by pljones** [comment] 2022-02-09 18:59
> However I did notice my selected (saved) country/region changed. Previous version (with Qt5) installed, I had selected Netherlands. Now with Qt6 my country is Mayotte. Not sure which issue is best to report this at.

[Qt6 compatibility](https://github.com/jamulussoftware/jamulus/pull/2299) is the only place I can think that would have happened.  The build you're running does have that included, yes?

**Comment by dcorson-ticino-com** [comment] 2022-02-09 19:29
>However I did notice my selected (saved) country/region changed. Previous version (with Qt5) installed, I had selected Netherlands. Now with Qt6 my country is Mayotte.

Looks like it is reading a Qt5 locale in the ini file and interpreting it as Qt6, or something similar.
If you change to Netherlands, exit Jamulus and start Jamulus again is the problem still there?

**Comment by hoffie** [comment] 2022-02-09 19:40
> I have tested the Qt6 build on a second win11 system and no issue with the display of the GUI. However I did notice my selected (saved) country/region changed. Previous version (with Qt5) installed, I had selected Netherlands. Now with Qt6 my country is Mayotte. Not sure which issue is best to report this at.

Thanks. Yes. I know about that part and the PR contains an open TODO item (` Do Country code conversion in Settings to ensure that updates continue working`).

**Comment by henkdegroot** [comment] 2022-02-09 20:43
> change to Netherlands, exit Jamulus and start Jamulus again is the problem still there?

Just to confirm, that the manual change, exit and start works. So just the TODO on the conversion part.

**Comment by hoffie** [comment] 2022-04-26 21:33
@ann0see Did I understand https://github.com/jamulussoftware/jamulus/pull/2300#issuecomment-1110251173 correctly that those glitches are no longer there on Windows since building with 6.3.0?

**Comment by ann0see** [comment] 2022-04-26 21:36
Yes – at least with the self compiled version.

**Comment by hoffie** [comment] 2022-04-26 21:38
Ok, maybe you can verify with the autobuild versions at some point and we could close this issue.

**Comment by ann0see** [comment] 2022-04-27 09:08
Yes. Windows 11 with the latest Qt version doesn't show these issues anymore. Still not sure about the iOS crash.

**Comment by ann0see** [comment] 2022-05-07 20:09
Closing this issue since the iOS crash is not related. Probably worth discussing in the linked PR.

**Closed by ann0see** 2022-05-07 20:09 UTC
Labels: bug
