### ISSUE TITLE
QFSFileEngine::open: No file name specified

### ISSUE THREAD

**Issue by yurivict** [jamulussoftware/jamulus#1311] opened 2021-03-20 04:59 UTC
**Describe the bug**
3.7.0 prints these error messages during regular activity like connecting to Jam rooms:
```
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
```

OS: FreeBSD 12.2

**Comment by jujudusud** [comment] 2021-03-20 07:51
Same thing apprends on Archlinux.

**Comment by gilgongo** [comment] 2021-03-20 08:12
This has been the case for most other releases. I believe it's not a problem but agree it would be nice not to have.

**Comment by dcorson-ticino-com** [comment] 2021-03-20 15:11
I think this has something to do with setting stylesheets in Qt.
I can make it worse, but I have not been able to reduce their number.
Note that there are also messages coming from some Qt type library that seem to be caused by some fonts being used by people in their user names.

**Comment by gilgongo** [comment] 2021-12-08 08:19
I think unless this is leading to some negative consequence, we can close this.

**Closed by gilgongo** 2021-12-08 08:19 UTC
Labels: bug

**Comment by softins** [comment] 2021-12-08 12:06
This was fixed in #1514
