### ISSUE TITLE
Memory leak in the server

### ISSUE THREAD

**Issue by corrados** [jamulussoftware/jamulus#923] opened 2021-01-29 20:48 UTC
I just observed the following on the Central Server: Right now we have heavy traffic on that server. The server run for about a month and the Jamulus server instance used about 500 MB. When I reboot the server, Jamulus just consumes about 4 MB.

I think the following code might be the problem:
https://github.com/jamulussoftware/jamulus/blob/ab785cb8d5e722663bb7887c8566a29a442ff86e/src/serverlogging.cpp#L65
We do a "new" all the time but do not delete that instance. Maybe it is better to completely remove the ConsoleWriterFactory() class and use QInfo instead.

**Comment by pljones** [comment] 2021-01-29 21:44
Yes, I'd back that, as we've moved to a dependency where `qInfo()` will always exist.  It'll need a little refactoring (as the messages format differently).

**Comment by corrados** [comment] 2021-01-29 22:14
Would you like to do it or shall I do this change?

**Comment by pljones** [comment] 2021-01-30 11:09
👍 I'll do it now - shouldn't take long.

**Comment by corrados** [comment] 2021-01-30 11:11
Thanks.

**Comment by pljones** [comment] 2021-01-30 14:40
Pull request: https://github.com/jamulussoftware/jamulus/pull/926

**Comment by hoffie** [comment] 2021-02-02 20:27
@pljones Now that #926 is merged, this could be closed?

**Comment by softins** [comment] 2021-02-03 13:00
> @pljones Now that #926 is merged, this could be closed?

If indeed that was the source of the leak. Time will tell!

**Comment by pljones** [comment] 2021-02-06 23:44
Yes, it's probably wise to monitor a server - preferably one that's long running and heavily used - to see if this the problem has gone away.

**Comment by pljones** [comment] 2021-02-17 19:35
Can we tag this as needing some kind of post-3.7.0 review (and hopefully then closing)?  I'd expect checking the process size on the Any Genre 1 directory server immediately after installing 3.7.0, then at intervals of a week for three weeks should provide enough information.  If the size is stable, it's fixed.

**Comment by genesisproject2020** [comment] 2021-02-17 21:28
I compiled the code yesterday (3.6.2dev-6d79bf1b) and it has now been running on "Swedish Open Jam 1" for 25h. During that time the amount of allocated memory went from 40Mb to, at the moment, 1Gb. I've also changed it on a private instance where a group had a rehearsal this evening with 12 members and after the 2h rehearsal the service have allocated 1,7Gb of memory and it is stuck there now when the instance is idle again. I do believe something is still eating the memory. Can I assist in someway to help finding the leak?

My environment: Ubuntu 20.04 LTS (5.4.0-65-lowlatency)

**Comment by genesisproject2020** [comment] 2021-02-17 21:39
I compiled the code yesterday (3.6.2dev-6d79bf1b) and it has now been running on "Swedish Open Jam 1" for 25h. During that time the amount of allocated memory went from 40Mb to, at the moment, 1Gb. I've also changed it on a private instance where a group had a rehearsal this evening with 12 members and after the 2h rehearsal the service have allocated 1,7Gb of memory and it is stuck there now when the instance is idle again. I do believe something is still eating the memory. Can I assist in someway to help finding the leak?

My environment: Ubuntu 20.04 LTS

**Comment by hoffie** [comment] 2021-02-17 22:08
@genesisproject2020 Do you have any pointers what could make this issue so visible in your environment? Any command line arguments? Number of concurrent users? Number of (re)connects? Chat messages? Level adjustments? Any pointers in reproducing it in a clean (valgrind-friendly) environment would probably help. :)

I seem to be able to trigger some things which make valgrind unhappy by running a server with two clients and having one client reconnect repeatedly, but I'll have to investigate when I've got more time.

**Comment by genesisproject2020** [comment] 2021-02-17 22:43
What I can see...
The clients connect about the same time and stay connected. 16 concurrent clients. I do not know what they do during their rehearsal when it comes to chat and level adjustments.

Command line: Jamulus --serverpublicip x.x.x.x -s -n -p 10001 -e directoryserver:10000 -F -l /mnt/www/private-server.log -R /mnt/recordings -o "Private Server;Stockholm;205" -m /mnt/www/private-server.dat -u 40 -T -w "Welcome!"

**Comment by softins** [comment] 2021-02-17 23:13
Whereas `valgrind` memory checking slows down the program by 10-30 times, which would probably make a Jamulus server unusable, it might be possible to use [`mtrace()`](https://man7.org/linux/man-pages/man3/mtrace.3.html) to collect allocation data. It does it using hooks to `malloc()`, `free()`, etc, rather than checking every memory access.

I might be able to give it a try tomorrow.

**Comment by hoffie** [comment] 2021-02-18 23:03
@genesisproject2020 I have opened a seperate issue (#1019) for analyzing the valgrind output which I generated in a lab setup which aims to mirror yours. I made it a seperate issue because the output is rather long. I also think that you might rather be hitting a different bug than what @corrados reported here initially. I think so because the increase seems to be really big and they might be related to the jam recorder (to be confirmed). I also assume that @corrados does not have recording enabled on the central server.

**Comment by pljones** [comment] 2021-02-20 22:02
Yes, I'd like to keep _this_ issue and the recording issue separate.

It would be good to have the issue here measured using valgrind, if someone could - i.e. run 3.6.2 without the recorder, check there's a problem; run the code with `ConsoleWriterFactory` removed and see if it made a difference.

If it was there and appears resolved, we can then close this without waiting further (as we've got a new issue for the JamRecorder leaks).

**Comment by softins** [comment] 2021-02-20 22:26
I think there are other issues too, apart from the recorder. @genesisproject2020 has been running my PR on his server, and memory is still climbing, even though the recorder shouldn't be leaking memory any more.

I notice that the valgrind output from @hoffie also showed some possible leaks to do with timers. That could explain memory usage still increasing. More investigation needed.

**Closed** 2021-09-14 09:07 UTC
Labels: bug
