### ISSUE TITLE
macOS: Allow r/w access outside of default ini file location

### ISSUE THREAD

**Issue by ToolTech** [jamulussoftware/jamulus#2131] opened 2021-11-23 11:49 UTC
Previously in pre 3.8.1 I could start multiple clients with different settings and the settings would be stored in separate config files. This way we could start multiple client for different devices and channels on a computer. (OS X)

In 3.8.1 this is mixed up. the names are lost and the settings are not stored. A Majord down step in functionality

**Comment by softins** [comment] 2021-11-23 14:56
This is because the MacOS version in 3.8.1 is signed with a developer signature, and as a result, apparently has to run in a Sandbox. I believe this is a standard feature of signed apps, but @emlynmac could advise more, as he implemented the signing for us.

So now, the default ini file is stored in `$HOME/Library/Containers/io.jamulus.Jamulus/Data/.config/Jamulus/Jamulus.ini`. If you give a filename to `-i`, then it needs to be a relative filename, not one starting with `/`, `~` or `$HOME`. This will then be relative to `$HOME/Library/Containers/io.jamulus.Jamulus/Data/`, so you could say `-i Config1.ini` to store the config in `.../Data` directly, or `-i .config/Jamulus/Config1.ini` to store it alongside the default ini file.

This definitely needs documenting - apologies - but it was an unforseen side-effect of making the app signed in order to avoid the "Unknown developer" warning on installation.

**Comment by softins** [comment] 2021-11-23 14:59
BTW, if you have your existing ini files, you can copy them to `~/Library/Containers/io.jamulus.Jamulus/Data/` or `~/Library/Containers/io.jamulus.Jamulus/Data/.config/Jamulus/` and the app should find them.

**Comment by ToolTech** [comment] 2021-11-23 15:16
And pretty strange to introduce this feature in a minor version ramp

Best regards!

/Anders Modén

**Comment by softins** [comment] 2021-11-23 15:28
> So you need to copy those files each time you install a new version then.

No, only the first time. The name of the data directory won't change in future versions.

> And pretty strange to introduce this feature in a minor version ramp

It was unexpected - well, it surprised me, at least.

**Comment by emlynmac** [comment] 2021-11-23 17:04
As we started signing the macOS release, this also means we support app sandboxing on the signed release. This is a security feature of macOS apps more recently, to ensure that they only have access to their files and nothing else.

**Comment by softins** [comment] 2021-11-23 17:07
> As we started signing the macOS release, this also means we support app sandboxing on the signed release. This is a security feature of macOS apps more recently, to ensure that they only have access to their files and nothing else.

How would this apply to other kinds of app, such as MuseScore, for example, or a text editor, which can read and write arbitrary files?

**Comment by emlynmac** [comment] 2021-11-23 17:11
> > As we started signing the macOS release, this also means we support app sandboxing on the signed release. This is a security feature of macOS apps more recently, to ensure that they only have access to their files and nothing else.
> 
> How would this apply to other kinds of app, such as MuseScore, for example, or a text editor, which can read and write arbitrary files?

Different apps can be set with different entitlements.
https://developer.apple.com/documentation/bundleresources/entitlements

**Comment by ann0see** [comment] 2021-11-28 20:48
… so basically Jamulus would need to have a new entitlement to read/write files?

**Comment by gilgongo** [comment] 2021-12-08 07:21
The config file location has been documented for the next website release.

@ann0see That would presumably mean the app would need to ask for permissions to write outside of its entitled space. I suppose that given the minority use of externally stored configs, such a warning would be OK. Better than the non-signed warning for all users at least.

**Comment by andresmattei** [comment] 2021-12-08 16:54
Im having issues as well with the server app writing permissions. Since updating, it cannot write into local directory in order to save recordings

**Comment by emlynmac** [comment] 2021-12-08 17:04
When we enabled App Store signing for the macOS app, we had to enable app sandboxing. This is a requirement for the Mac app store.
There are some restrictions here, which some users are finding around global file writing.

Some thoughts.
1. Does the un-signed release from the jamulus GitHub page work? 
2. The sandboxed app has file writing permissions, just to a specific area of the filesystem and so do recordings get saved there or not?
3. We probably need to do a pass on the code to ensure that we write files only to the sandboxed area and document that.

**Comment by softins** [comment] 2021-12-08 17:14
> When we enabled App Store signing for the macOS app, we had to enable app sandboxing. This is a requirement for the Mac app store. There are some restrictions here, which some users are finding around global file writing.

How would these requirements differ for Jamulus, compared to an app such as MuseScore, which seems able to read and write files anywhere in the filesystem? The MuseScore app for Mac is signed, I believe, but I don't know whether it is available via the App Store, or just the MuseScore website.

Is it possible to sign apps just for installation, with no expectation of using the App Store, and therefore perhaps no need to sandbox? I don't think the App Store gives us much benefit.

**Comment by softins** [comment] 2021-12-08 17:16
> 1. Does the un-signed release from the jamulus GitHub page work?

@ToolTech you should be able to find that [here](https://github.com/jamulussoftware/jamulus/releases/tag/r3_8_1)

**Comment by andresmattei** [comment] 2021-12-08 20:42
> > 1. Does the un-signed release from the jamulus GitHub page work?
> 
> @ToolTech @andresmattei you should be able to find that [here](https://github.com/jamulussoftware/jamulus/releases/tag/r3_8_1)

Got same result:
![Screen Shot 2021-12-08 at 2 41 50 PM](https://user-images.githubusercontent.com/95768540/145281351-7c89a643-a600-4d6d-b32c-d0f97f93f110.png)

**Comment by andresmattei** [comment] 2021-12-08 20:49
> 2. The sandboxed app has file writing permissions, just to a specific area of the filesystem and so do recordings get saved there or not?

They do get saved in a specific directory in the filesystem, just can't change to a local folder outside the app like previously:
![Screen Shot 2021-12-08 at 2 46 27 PM](https://user-images.githubusercontent.com/95768540/145282079-b3de31da-84c3-45df-be05-84494a9c22e2.png)

**Comment by ToolTech** [comment] 2021-12-08 21:35
Nope!

3.8.0 Works !

the git version doesn’t work

**Comment by ToolTech** [comment] 2021-12-08 22:00
Doesnt work 

Best regards!

/Anders Modén

**Comment by ann0see** [comment] 2021-12-28 09:39
Did you try the legacy version?

**Comment by ann0see** [comment] 2021-12-28 09:41
IMHO this needs fixing. Probably it’s just adding entitlements?

@emlynmac

**Comment by ann0see** [comment] 2021-12-28 09:45
We might be able to invoke the system file manager. Maybe this helps requesting write access?

**Comment by ToolTech** [comment] 2021-12-28 09:52
Didnt work 

Best regards!

/Anders Modén

**Comment by ann0see** [comment] 2021-12-28 19:24
That's a pitty. I assume you removed the signed version and then installed the [legacy version](https://github.com/jamulussoftware/jamulus/releases/download/r3_8_1/jamulus_3.8.1_mac_legacy.dmg)? If that's the case, we might need to change something in the legacy version build process. 

What can we practically do here?

Research how to set entitlements to allow writing into arbitary folders?
Implement a feature to open the standard OS file manager?

**Comment by ginjo** [comment] 2022-04-11 04:23
I can confirm that the r3_8_2nightly1 build creates, reads, and writes the ini files in the location of my choosing, just as it worked in 3.8.0. Not sure if that solves all of the above poster's issues, but it seems to solve the OP's issue, and it has me back on track again.

One use case that I don't think I've seen mentioned is this: I have several folders of ini files, with each folder containing my instrument/mic setup for a different band (or different role with a different group of musicians). The flexible functionality of the ```--inifile``` option allows me to easily set up  multiple instruments and connect with the band of my choice.

So a big thanks to the devs for this feature and for bringing it back to life!

**Comment by ann0see** [comment] 2022-04-22 19:32
@ToolTech does  the following version also work for you: https://github.com/jamulussoftware/jamulus/discussions/2400

If yes, this issue and #2592 should be closed since they are duplicates.

**Comment by ann0see** [comment] 2022-04-24 05:58
Ah sorry. @ToolTech I linked something wrong. Could you please test https://github.com/emlynmac/jamulus/suites/6225519742/artifacts/220637083

**Comment by ann0see** [comment] 2022-05-07 20:06
Closing due to no response. @ginjo seems to be able to verify this issue is fixed in the next release.

**Comment by ann0see** [comment] 2023-02-13 15:13
Re opening as I don't think this is fixed.

We should probably drop the DontUseNativeDialog here: https://github.com/jamulussoftware/jamulus/blob/main/src/serverdlg.cpp#L627 and here https://github.com/jamulussoftware/jamulus/blob/main/src/serverdlg.cpp#L603

**Comment by ginjo** [comment] 2023-02-13 22:56
I can confirm that the latest build of Client ```jamulus_3.9.1dev-2f352ef_mac``` does not work as it did when I tested with ```Jamulus_382dev_apr9``` (see comment above).

No .ini file is save per the ```-i``` option, and no settings are saved when quit and relaunched. Here is output from the CLI:

~~~
/Applications/Jamulus_3.9.1dev-2f352ef/Jamulus.app/Contents/MacOS/Jamulus --clientname Guitar -i '/Users/wbr/jamulus_3.9.1dev-2f352ef'.ini
- client name: Guitar
- initialization file name: /Users/wbr/jamulus_3.9.1dev-2f352ef.ini
- allocated port number: 22134
~~~

Just to restate my use case: I have several folders of multiple .ini files. Each folder is for a different role/project/session that I collaborate on, and each .ini file is a different source/instrument that I contribute to the session. I have a bash script that launches all of the .ini files in a folder. This setup saves me a lot of time getting a session started and running properly and is why I'm still running ```Jamulus_382dev_apr9``` for all of my sessions.

Happy to do more testing or help any way I can.

**Comment by ann0see** [comment] 2023-02-14 07:47
@ginjo 

Can you copy the files into your Library folder? See https://github.com/jamulussoftware/jamulus/pull/2563#issuecomment-1081947711

**Comment by ginjo** [comment] 2023-02-16 22:40
Yes, that does work. I could live with it, as long as the ini files aren't overwritten or destroyed by Jamulus or some OS housecleaning operation (Sorry, not familiar with the sandboxing feature). Thanks!

**Comment by ann0see** [comment] 2023-02-17 07:05
Unfortunately I don't know if the OS removes these files. Jamulus shouldn't. You can backup them. Or adapt your script to do that.

**Comment by ginjo** [comment] 2023-02-18 07:04
Good to know, thanks. That will work fine.

**Comment by ann0see** [comment] 2023-07-01 20:29
I think the ini files in arbitrary folders don't work with signing. I think this is probably a wont fix. @gilgongo are the Docs up to date?

**Comment by gilgongo** [comment] 2023-07-18 13:18
@gilgongo I think we were waiting to see whether it could be fixed. But if not, and assuming the signed binary will be the dominant one, then would we need to add something to `--inifile` perhaps along the lines of "Does not work for macOS"?

**Comment by ann0see** [comment] 2023-07-18 14:15
It DOES work on macOS, but only in specific folders. Just giving a file name should be enough. Then it's hidden in some sandbox path.

**Comment by gilgongo** [comment] 2023-07-19 07:30
OK so it'll need something that [explains it like this](https://github.com/jamulussoftware/jamulus/issues/2131#issuecomment-976669134), I take it? Something like:

_"On macOS, the path to the file must not start with /, ~ or $HOME. It must be relative to $HOME/Library/Containers/io.jamulus.Jamulus/Data/ (so a file name with no path is recommended). Note that the legacy version of Jamulus does not have this restriction."_

**Comment by ann0see** [comment] 2023-07-19 11:02
I don't think macOS users know about $HOME as environment variable. We need to check what its content is by default. Probably something like /Users/<Username>

**Comment by ann0see** [comment] 2023-07-28 19:38
Dropped needs documentation as this is now handled in https://github.com/jamulussoftware/jamuluswebsite/pull/936

**Comment by ann0see** [comment] 2023-07-28 19:41
Closing for now as not planned. It's not perfect but I think with the documentation, we have a small step. Please re-open if still pressing.

**Closed by ann0see** 2023-07-28 19:41 UTC
Labels: feature request

**Comment by gilgongo** [comment] 2023-07-28 21:32
> We need to check what its content is by default. Probably something like /Users/<Username>

Looks like it's:

/Users/<username>/Library/Containers/io.jamulus.Jamulus/Data/.config/Jamulus/

The only way of getting there is to either use the CLUI or turn on "Show Library folder" in "Show view options" in the Finder.

So maybe something like:

"On macOS, the path to the file must be relative to `/Users/<username>/Library/Containers/io.jamulus.Jamulus/Data/.config/Jamulus/` (turn on "Show Library folder" in "Show view options" in the Finder to see this). So a file name with no path is recommended. Note that the legacy version of Jamulus does not have this restriction."

**Comment by ann0see** [comment] 2023-07-29 10:49
Agree. This should be discussed in the linked PR.
