### ISSUE TITLE
Display a slider control for level / sensitivity of the active input device

### ISSUE THREAD

**Issue by S-luap** [jamulussoftware/jamulus#678] opened 2020-10-16 19:11 UTC
I’m a member of a mens barbershop chorus and we’re just getting up and running with Jamulus for our online rehearsals. We’re using our own Jamulus server installation on a 4-core machine, making use of the recent enhancement to allow multi-threading. We had 24 members on last night’s rehearsal session; 12 others are Jamulus-enabled but couldn’t make the session, and we have 11 more waiting in line to get up and running. Our ambition is to get all 47 members participating in online rehearsals using Jamulus (as well as breaking out into parallel smaller groups for sectional and small group work). Whilst the current pandemic prevents us from meeting up in person, having Jamulus available and accessible to our members so they can sing together in real time is absolutely amazing.

I have a feature request to submit, for an enhancement which (if it’s feasible) would be really helpful for some of our more technically-challenged members:-
 
When users need to turn their microphone sensitivity up or down, they have to navigate through to the relevant Windows control panel settings. It would be really helpful if the Jamulus client window displayed a slider control to adjust the sensitivity directly from within the application.

(I’m a new member to this community, so apologies if this is not the appropriate way to submit a feature / enhancement request).

**Comment by chrisrimple** [comment] 2020-10-17 00:45
@S-luap Also a barbershopper, so I understand your concerns.  The difficulty will be that adjusting sensitivity means (1) knowing what audio device is being used and (2) being able to adjust it, which is going to be different on Windows, Mac, and Linux.  For example, I'm on a Mac, and with Jamulus have at least two audio devices available: System (aka sound card in my computer) and Audio Interface.  Jamulus would need to know how to change the input (microphone) sensitivity for each one.  Now multiply that by the number of different Audio Interface manufacturers, models, etc. and it becomes a monumental task.

A simplified solution might be to add a button to the Jamulus window for "Adjust System Volume" or similar.  When clicked, it opens the default System sound controls (for Windows, Mac, and Linux).  Since many choral/barbershop users of Jamulus do not have Audio Interfaces and are using their computer's sound card, this would at least give them quick access to the System input (microphone) controls.

Going further, a slider like you describe, that would adjust ONLY System input sensitivity, might be possible.  I defer to the developers to articulate the ease or difficulty.

**Comment by gilgongo** [comment] 2020-10-17 11:43
This sounds related https://github.com/corrados/jamulus/issues/97

**Comment by kwindrem** [comment] 2020-10-19 00:14
I think this is different than a master level for the mixer output. 

I believe S-luap is asking to adjust the sound card's input sensitivity (aka gain) from within Jamulus. As chrisimple suggests, this could get complicated in a hurry. Opening the system sound input control panel might be possible but if Jamulus is using an external interface, the input gain control generally won't be available in software. Gain could be added in Jamulus after the soundcard selection but you would not be able to turn down if clipping occurs. Adding gain would add noise but might be a half-solution.

**Comment by chrisrimple** [comment] 2020-10-19 00:25
Opening the System Sound input control might go nicely with the Basic mode in #[681](https://github.com/corrados/jamulus/issues/681), particularly for choral users that are unlikely to have an external interface.

**Comment by S-luap** [comment] 2020-10-19 09:06
We have one or two members who use an external interface, they either have controls on that device to adjust microphone gain, or are savvy enough to know how to do it. I’m looking more at helping the non-technical users by providing a more direct and simple way to adjust their microphone volume in-situ. These are folks who, when they’re told “we can hardly hear you / you’re hitting the red all the time and clipping, you need to adjust your mic volume” reply “how do I do that?”. 

Admittedly the problem affects new users to Jamulus who are technically challenged, and eventually goes away as they get more practiced with the system, but it’s still adds to their difficulties during that learning stage. As we bring more users on board, and start rolling out to other choruses, it will be a recurring obstacle to be dealt with. We’re providing user documentation, which will help, but it still requires the user to step out of Jamulus and take a tortuous detour into various Windows settings dialogues.

I was thinking along the lines of something like you see in the Zoom Windows app, where you can get quickly to a sounds settings dialogue, within Zoom itself, that exposes a slider control for microphone sensitivity, or like you see in Audacity, where there’s a mixer toolbar with a mic icon and slider that controls recording volume.

Maybe it’s not possible, or technically too complex, but it would be a nice feature to have.

**Comment by kwindrem** [comment] 2020-10-19 15:14
I checked and Zoom does adjust the Mac's input control panel's gain (sensitivity) with it's slider. For other interfaces, Zoom still provides a slider but can't actually adjust the microphone preamp's gain so I think it's just attenuating the signal after it gets into Zoom. There's no boost of level in this case.

**Comment by S-luap** [comment] 2020-10-19 17:51
I did a quick test on my Windows 10 laptop. Opened up the Windows “Sound” panel and then the “Microphone Properties” panel and selected the “Levels” tab. Then opened up Zoom, started a meeting using computer audio, opened up the “Audio Settings” panel and displayed it side-by-side with the Windows “Microphone Properties” panel. Moving the slider in either panel moves the slider in the other panel in sympathy. I’ve attached two screenshots (hopefully) to show the dialogues I mean, and the sliders. Not entirely sure if this is controlling preamp gain or just attenuating the volume between zero and current available maximum, but it seems to have the desired effect - and using the same Windows “Microphone Properties” panel slider achieves the desired result for sound input to Jamulus - it’s just a bit fiddly to step outside of Jamulus, navigate through several cascading windows (5 mouse clicks to get to the “Microphone Properties”) to access the slider.

![8099D3DA-78ED-47AC-A354-A489542D46B9](https://user-images.githubusercontent.com/72995413/96491354-0965c600-123a-11eb-8fa5-a565ae2e2f47.jpeg)
![8164C8E8-E841-4036-A89A-CC9D6C566C28](https://user-images.githubusercontent.com/72995413/96491362-0b2f8980-123a-11eb-847f-42700862db92.jpeg)

**Comment by sthenos** [comment] 2020-10-28 00:05
I don't see why this couldn't work any differently that a carla plugin that allows you to control the input gain that is coming into the plugin.   It doesn't affect the gain on the mic itself, just allows you to control the input sound coming into software.   I agree, that having a simple dial at the top of the Input section that allows you to control the overall input level coming into jamulus at a software level would be beneficial.

**Comment by chrisrimple** [comment] 2020-10-30 07:02
@sthenos I believe that you’re suggesting Jamulus control input gain level of what it’s receiving, meaning 1-100% of (input).  But if (input) is too low, then setting Jamulus gain to 100% won’t help.  The ask here is to control (input) directly, at least in those cases where (input) = System Input. The Zoom example above illustrates the desire.

**Comment by kwindrem** [comment] 2020-10-30 15:31
There may be a couple of different things here:

Microphone preamp gain: control over the (usually) first gain stage after the microphone. Most external interfaces use a physical knob for this so it's not possible to make a gain change remotely. In addition, if the gain is too high, the mic will clip the preamp and there's nothing that can be done down stream to correct it. If the gain is too low, adding gain down stream can bring the signal up to a workable level but this also adds noise. It is true that some mic levels can be adjusted as can be seen in sound control panels for the internal microphone, but how many people are using internal microphones (or external audio interfaces with remote preamp gain adjustment) with Jamulus? 

A "trim" on levels after they have been converted to digital to bring levels into the useable range of the main slider. For example, if the main slider for a channel is all the way up but it's still not loud enough, the trim can add gain so the fader can reach the desired level in the mix.

Some find the Jamulus user interface intimidating already. Any addition of "channel trim" needs to be done in such a way as to not complicate the user interface for less skilled users, e.g., additional dialogs activated by "Advanced" buttons.

**Comment by chrisrimple** [comment] 2020-10-30 15:36
The original post is referring to Jamulus users without an external audio interface, that are just using the computer's built-in soundcard, and is focused on control of System input (mic) level via a slider in Jamulus.

**Comment by gilgongo** [comment] 2021-02-19 11:54
Hi all - this issue is pretty old, is probably a duplicate of #97 and may well be out of the scope of what Jamulus is really about (device audio issues aren't really Jamulus's responsibility). So I'll close this now. If you want to debate further, please do so in [Discussions](https://github.com/jamulussoftware/jamulus/discussions) though.

**Closed by gilgongo** 2021-02-19 11:54 UTC
Labels: feature request
