### ISSUE TITLE
Ubuntu 18.04: Version 3.8.2 fails to install due to bad dep libgcc-s1 (>= 3.0)

### ISSUE THREAD

**Issue by reinhardwh** [jamulussoftware/jamulus#2422] opened 2022-02-22 19:48 UTC
### Discussed in https://github.com/jamulussoftware/jamulus/discussions/2416

Tried to update server to 3.8.2

Error returned:

root@rv2575:~# sudo apt install ./jamulus_headless_**3.8.2**_ubuntu_amd64.deb
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Hinweis: »jamulus-headless« wird an Stelle von »./jamulus_headless_3.8.2_ubuntu_amd64.deb« gewählt.
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 jamulus-headless : Hängt ab von: **libgcc-s1 (>= 3.0) ist aber nicht installierbar**
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.

**Comment by hoffie** [comment] 2022-02-22 20:04
Thanks for the report. Can you please provide the following details:
- Is this Ubuntu or Debian? Which version? (`lsb_release -a` output would help if this command is available)
- You've linked to the discussion about script based installations vs. packages, so I'm assuming that this is your first attempt at using Jamulus debian packages, right? In other words: You didn't have 3.8.1 or some other version installed as a package before, right?

>  Hinweis: »jamulus-headless« wird an Stelle von »./jamulus_headless_3.8.2_ubuntu_amd64.deb« gewählt.

This sounds a bit strange. You could try installing by `dpkg` directly to see where that leads.

```
export LANG= LC_ALL=C  # English error messages
dpkg -i  ./jamulus_headless_3.8.2_ubuntu_amd64.deb
apt-get install -f
```

**Comment by reinhardwh** [comment] 2022-02-22 20:13
root@rv2575:~/jamulus-latest/jamulus-latest# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

**Comment by reinhardwh** [comment] 2022-02-22 20:15
root@rv2575:~# dpkg -i  ./jamulus_headless_3.8.2_ubuntu_amd64.deb
(Reading database ... 211071 files and directories currently installed.)
Preparing to unpack .../jamulus_headless_3.8.2_ubuntu_amd64.deb ...
Unpacking jamulus-headless (3.8.2) over (3.8.1-0) ...
dpkg: dependency problems prevent configuration of jamulus-headless:
 jamulus-headless depends on libgcc-s1 (>= 3.0); however:
  Package libgcc-s1 is not installed.

dpkg: error processing package jamulus-headless (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 jamulus-headless

**Comment by reinhardwh** [comment] 2022-02-22 20:17
Installed 3.8.1 as a package before 
No issues during install

**Comment by reinhardwh** [comment] 2022-02-22 20:19
Did a manual compile - now server is on 3.8.2

**Comment by reinhardwh** [comment] 2022-02-22 20:32
New version 3.8.2 seems to improve latency compared to 3.8.1
Thanks for all the hard work!

**Comment by hoffie** [comment] 2022-02-22 22:28
- I've reproduced this issue in a Ubuntu 18.04 container. I've no idea yet where it comes from, but it seems like the 3.8.2 .deb is broken for Ubuntu 18.04. `dpkg -i *.deb` works with warnings, but `apt install -f` will remove it again.
- 3.8.1devNightly1-6b0233d  is broken as well
- 3.8.1 (final) works

To rule out any Ubuntu build environment changes, we should try a fresh 3.8.1 build.

**Comment by hoffie** [comment] 2022-02-22 23:08
The 3.8.2 release used Ubuntu 18.04.6: https://github.com/jamulussoftware/jamulus/runs/5265416093?check_suite_focus=true#step:1:4
3.8.1 logs are no longer downloadable.

I first suspected this issue to be relevant: https://github.com/actions/virtual-environments/issues/2816
Workarounds:
- Downgrade packages: https://github.com/tautschnig/cbmc/commit/8514130ae0adf93a4113e67287faa2dbc0b8d462#diff-e74242bf286d59a170959f9db157b5f7171508ca1f040240ed9c1591b6a88429
- Use a container

However, [a fresh build of 3.8.1](https://github.com/hoffie/jamulus/actions/runs/1884332500) does not exhibit the issue. This pints to a problem with one of our changes. I currently suspect 86807c1ab88ee10ab453371b45d3a4e8a45fd606 from #2138 which dropped logic to update the `debian/control` file although the commit message makes no mention that this was by intention. I'll try a 3.8.2 build with this part reverted.

**Comment by hoffie** [comment] 2022-02-22 23:15
I've not yet confirmed that this is the culprit, but it is at least a bug and causes unintended effects:
```
root@71dafa5ca28f:/downloads# dpkg-deb --info jamulus_headless_3.8.1_ubuntu_amd64.deb | grep -P 'Depends|Maintainer'
 Maintainer: "corrados" <nomail@example.com>
 Depends: libqt5core5a (>= 5.5.0), libqt5network5 (>= 5.0.2), libqt5xml5 (>= 5.0.2)

root@71dafa5ca28f:/downloads# dpkg-deb --info jamulus_headless_3.8.2_ubuntu_amd64.deb | grep -P 'Depends|Maintainer'            
 Maintainer: "Marc Landolt jr" <debian@marclandolt.ch>
 Depends: libc6 (>= 2.27), libgcc-s1 (>= 3.0), libqt5core5a (>= 5.9.0~beta), libqt5network5 (>= 5.8.0), libqt5xml5 (>= 5.0.2), libstdc++6 (>= 7), adduser
```

```
$ grep Maintainer $(find -name control)
./distributions/debian/control:Maintainer: "Marc Landolt jr" <debian@marclandolt.ch>
./distributions/autobuilddeb/control:Maintainer: "The Jamulus Development Team" <team@jamulus.io>
```

**Comment by hoffie** [comment] 2022-02-22 23:54
@reinhardwh You can try the following inofficial .deb by me which is 3.8.2 (code-wise), but should fix this issue:
https://github.com/hoffie/jamulus/suites/5409403458/artifacts/170815896

Feedback welcome! :) (And as stated: Your setup might seem to work, but jamulus-headless will likely be removed when `apt` gets a chance to "fix" installed packages)
Thanks again for reporting this!

Further discussion regarding resolving this for all users is likely to occur on the PR #2423.

**Comment by reinhardwh** [comment] 2022-02-23 06:44
Hello @hoffie 
tried to install your inofficial .deb

1020 -rw-r--r--  1 root root 1041404 Feb 23 07:30 jamulus_headless_3.8.2_ubuntu_amd64.deb
`
root@rv2575:~# sudo apt install ./jamulus_headless_3.8.2_ubuntu_amd64.deb
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Probieren Sie »apt --fix-broken install«, um dies zu korrigieren.
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 jamulus-headless : Hängt ab von: libgcc-s1 (>= 3.0) ist aber nicht installierbar
E: Unerfüllte Abhängigkeiten. Versuchen Sie »apt --fix-broken install« ohne Angabe eines Pakets (oder geben Sie eine Lösung an).
`
**Repair Installation** 
`root@rv2575:~# apt --fix-broken install
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Abhängigkeiten werden korrigiert ... Fertig
Die folgenden Pakete werden ENTFERNT:
  jamulus-headless
0 aktualisiert, 0 neu installiert, 1 zu entfernen und 10 nicht aktualisiert.
1 nicht vollständig installiert oder entfernt.
Nach dieser Operation werden 1.989 kB Plattenplatz freigegeben.
Möchten Sie fortfahren? [J/n] j
(Lese Datenbank ... 211071 Dateien und Verzeichnisse sind derzeit installiert.)
Entfernen von jamulus-headless (3.8.2) ...
root@rv2575:~#
`
**New Installation:** 

`root@rv2575:~# sudo apt install ./jamulus_headless_3.8.2_ubuntu_amd64.deb
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Hinweis: »jamulus-headless« wird an Stelle von »./jamulus_headless_3.8.2_ubuntu_amd64.deb« gewählt.
Die folgenden NEUEN Pakete werden installiert:
  jamulus-headless
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 10 nicht aktualisiert.
Es müssen noch 0 B von 1.041 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 1.989 kB Plattenplatz zusätzlich benutzt.
Holen:1 /root/jamulus_headless_3.8.2_ubuntu_amd64.deb jamulus-headless amd64 3.8.2 [1.041 kB]
Vormals nicht ausgewähltes Paket jamulus-headless wird gewählt.
(Lese Datenbank ... 211066 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../jamulus_headless_3.8.2_ubuntu_amd64.deb ...
Entpacken von jamulus-headless (3.8.2) ...
jamulus-headless (3.8.2) wird eingerichtet ...
N: Der Download wird als root und nicht Sandbox-geschützt durchgeführt, da auf die Datei »/root/jamulus_headless_3.8.2_ubuntu_amd64.deb« durch den Benutzer »_apt« nicht zugegriffen werden kann. - pkgAcquire::Run (13: Keine Berechtigung)
`
**Installation successful**.

**Comment by hoffie** [comment] 2022-02-23 11:43
Thanks for testing -- looks good (I took the freedom to improve the code formatting in your comment).

**Comment by hoffie** [comment] 2022-02-23 19:57
Reopening this issue as the release binary still needs updating.
Currently running a build here which hopefully outputs a 3.8.2-1 .deb: https://github.com/hoffie/jamulus/tree/autobuild-3.8.2-1-debian https://github.com/hoffie/jamulus/runs/5309389996?check_suite_focus=true

**Comment by hoffie** [comment] 2022-02-23 22:27
That worked (despite the artifact name, which is fixable).
The resulting debs both install fine on Ubuntu 18.04 for me. apt and dpkg show the proper -1 debian_revision as we wanted it, while the in-app version is unchanged at 3.8.2.

```
root@515471bef655:/downloads/3.8.2-1# dpkg -l | grep jamulus
ii  jamulus-headless            3.8.2-1                   amd64        Low latency Audio Server (headless)
root@515471bef655:/downloads/3.8.2-1# apt-cache show jamulus-headless | grep Ver
Version: 3.8.2-1
root@515471bef655:/downloads/3.8.2-1# jamulus-headless --version
 *** Jamulus, Version 3.8.2
```

```
root@515471bef655:/downloads/3.8.2-1# dpkg -l | grep jamulus   
ii  jamulus                       3.8.2-1                       amd64        Low latency Audio Server/Client
root@515471bef655:/downloads/3.8.2-1# apt-cache show jamulus | grep Ver
Version: 3.8.2-1
root@515471bef655:/downloads/3.8.2-1# jamulus --version
 *** Jamulus, Version 3.8.2
```

**Comment by hoffie** [comment] 2022-02-23 22:44
So, this should be fixed now.

- [x] Uploaded the 3.8.2-1 artifacts to the release & removed the broken .debs (we can still get them from the actions tab, IIRC)
- [x] Added note to release (at the top)
- [x] Posted a comment to the release announcement: https://github.com/jamulussoftware/jamulus/discussions/2410#discussioncomment-2239889
- [x] Pushed the source as tag [debonly_r3_8_2-1](https://github.com/jamulussoftware/jamulus/tree/debonly_r3_8_2-1) to jamulussoftware/jamulus (prefixed to avoid autobuilds/releases) for archival reasons
- [ ] @softins Can you post a comment on Facebook, if you think it's worth it?
- [ ] Close this issue (when FB is done) @softins?

**Comment by softins** [comment] 2022-02-23 23:46
Posted this:
>Just a quick heads-up for anyone wanting to install 3.8.2 on Ubuntu using the Jamulus .deb packages on the release page. There was an error in the original release packages, which caused package installation to fail.
> We have re-made the packages and replaced the original ones on the 3.8.2 release page. The correct Ubuntu packages have 3.8.2-1 in the filename, although the installed version of Jamulus is still 3.8.2.
> If anyone encountered this installation issue, please try again with one of the new packages.

@gilgongo I see the Sourceforge copies still need to be updated.

**Closed** 2022-02-24 07:47 UTC

**Comment by reinhardwh** [comment] 2022-02-24 21:59
Thanks for fixing so quickly!
