### ISSUE TITLE
UI: Reverb slider off-center in MacOS as of 3.9.0 / Qt6

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#2772] opened 2022-08-07 20:25 UTC
### Discussed in https://github.com/orgs/jamulussoftware/discussions/2768

<div type='discussions-op-text'>

<sup>Originally posted by **rdica** August  1, 2022</sup>
This was first reported to me from an associate using Jamulus 3.9.0 MacOS Monterey. I upgraded my client on MacOS Catalina and see the same thing, the reverb slider is off-center.

No issues on Ubuntu 18.04 with QT 5.9.5.

Jamulus 3.9.0, QT 6.3.1, main MacOS build.
(I installed the legacy dmg, it runs on MacOS Catalina and it does not display the reverb slider off-center. Its QT version is 5.9.9.)

Catalina:
<img width="176" alt="Screen Shot 2022-08-01 at 3 34 57 PM" src="https://user-images.githubusercontent.com/16609801/182231338-87f4176e-b725-4169-9ba2-21067086ace8.png">

Monterey:
![Screenshot_2022-08-01_15-38-16](https://user-images.githubusercontent.com/16609801/182231587-b3c68199-255a-433f-9f0b-51295c1362e9.png)
.</div>

**Comment by hoffie** [comment] 2022-08-07 20:31
@rdica Thanks for the report. This sounds like this unresolved Qt bug: https://bugreports.qt.io/browse/QTBUG-98903 :(

I guess it might be possible to find workarounds by adjusting specific style options or [painting manually](https://stackoverflow.com/questions/69890284/qslider-in-qt-misbehaves-in-new-macos-monterey-v12-0-1-any-workaround/69890285#69890285), but I'm not sure if we want to do the latter. It would also be good to have someone on Mac OS develop/test this fix as this would certainly benefit from a tight feedback loop...

I'm adding a 3.9.1 target for now, but it might well be possible that we'll have to postpone it until a fixed Qt version is available.

**Comment by hoffie** [comment] 2022-08-12 22:51
> I tried each skin and the reverb slider was off-enter in each.

@rdica Could you please also check the other faders in the settings dialog, are they affected as well (network buffers, input balance; screenshots would help)?

**Comment by hoffie** [comment] 2022-08-12 23:15
@rdica Two other things to try (not really expecting an improvement though...):
1. QSlider with empty stylesheet ([Assets](https://github.com/hoffie/jamulus/actions/runs/2849817981))
1. QSlider with dummy stylesheet ([Assets](https://github.com/hoffie/jamulus/actions/runs/2849826922))

**Comment by rdica** [comment] 2022-08-16 22:44
@hoffie Apologies for the delayed response....I tried both builds, using all skins, same results; still off-center.

**Comment by rdica** [comment] 2022-08-16 23:02
Screenshots of Settings dialog faders each of 3.9.0, and the two dev builds:

3.9.0
<img width="438" alt="3 9 0" src="https://user-images.githubusercontent.com/16609801/184999532-8e3fac7c-f937-455e-8cdb-09cdf078ef6d.png">

3.9.0dev-d95ebaa
<img width="438" alt="3 9 0-d95xxxx-build" src="https://user-images.githubusercontent.com/16609801/184999539-d6155b1e-6ad4-44c6-ad96-a35b38339a89.png">

3.9.0dev-e08c36b
<img width="436" alt="3 9 0-e08xxxx-build" src="https://user-images.githubusercontent.com/16609801/184999545-28e257ea-4202-433f-aa2a-ea188a9c5d9b.png">

**Comment by hoffie** [comment] 2022-08-19 08:17
Thanks for the feedback! So somehow the technically similar faders in the settings dialog are not affected. I'll try to dive into potential differences.

**Comment by rdica** [comment] 2022-08-19 14:22
Sorry, did I miss something, the sliders in the above screenshots look off-center, same as the reverb slider...

**Comment by hoffie** [comment] 2022-08-19 14:41
Hmm, sorry, I seem to have missed some details. I do see a slight mis-rendering of the knob (the ticks on the left are less overlapped by the knob compared to the right), is this what you mean?
Or do you mean the layout of the whole slider, which seems to be slightly off compared to the header text?

**Comment by rdica** [comment] 2022-08-19 15:18
The former, same as it appears for the reverb slider, sorry.

**Comment by pljones** [comment] 2022-09-04 10:13
Do we have anyone able to look into the cause on this?  I'd like to know where the bug was introduced.  @hoffie, as it's likely to be some change to the build dependencies, is this something you could pick up?

**Comment by pljones** [comment] 2022-09-07 12:32
It's worth a look at the screenshots [from the issue mentioned above](https://github.com/jamulussoftware/jamulus/issues/2723#issuecomment-1239293096).  It could be more evidence the issue isn't the Qt version itself but somewhere else in the build process.

**Comment by pljones** [comment] 2022-09-17 11:16
Moving to 3.10.0.  If there's no progress there, it'll get closed.

**Comment by pljones** [comment] 2023-04-19 16:10
If someone has a fix for this, please raise the PR and reference this bug.

**Closed by pljones** 2023-04-19 16:10 UTC
Labels: bug
