### ISSUE TITLE
Disabled Loudspeaker Symbol not shown when Mono channel configuration (duplicate of #1074)

### ISSUE THREAD

**Issue by pappou99** [jamulussoftware/jamulus#1324] opened 2021-03-22 20:31 UTC
**Description**
When channel configuration is set to mono, no signalisation is show, if others muted me. (cancelled loudspeakersymbol is missing)

**To Reproduce**
Settings -> Audio Channels -> Mono
Connect to server with other participiants. Please them to mute your channel. Now it should show you, that the other isn't hearing you, but no signalisation is shown.
Settings -> Audio Channels -> Mono in / Stereo out
Signalisation that others muted you is shown (disabled loudspeaker symbol)

**Expected behavior**
Signalisation that others muted you is shown in any channel configuration (disabled loudspeaker symbol)

**Operating system**
Win10Pro, Ubuntu

**Version of Jamulus**
3.7.0 also in 3.6.2
**Additional context**
if configured to mono, the pan knob disappears and the fader grows. Perhaps the loudspeakersymbol is part of the pan module in gui?

**Comment by gilgongo** [comment] 2021-03-23 22:40
Sorry, if this is a dupe of https://github.com/jamulussoftware/jamulus/pull/1074 do you mind if I close it?

**Comment by pappou99** [comment] 2021-03-24 06:22
> Sorry, if this is a dupe of #1074 do you mind if I close it?

No, please do so.

**Comment by ann0see** [comment] 2021-03-24 21:51
Closed since there's an open Pull request

**Closed** 2021-03-24 21:51 UTC
Labels: duplicate

**Comment by gilgongo** [comment] 2021-03-25 07:49
OK, but manually closing is just more work as it would have been closed automatically when the PR was merged. But it's not a big deal.

**Comment by ann0see** [comment] 2021-03-25 10:45
Yes. You're right. But let's leave it like that.

**Comment by gilgongo** [comment] 2021-03-25 12:33
Oh actually it was a duplicate anyway - hehe. Never mind!
