### ISSUE TITLE
MacOS: using a ZoomR24 as audio interface does not work

### ISSUE THREAD

**Issue by roelbakker123** [jamulussoftware/jamulus#3267] opened 2024-04-18 09:09 UTC
I try to use my Zoom R24 as an audio interface. Even if I choose the right driver/audio interface in Jamulus for both input and output, Jamulus does not 'hear' the microphone which is attached to the R24. Privacy settings in OSX are taken care of, so that can't be the issue. Has anyone an idea what can be the matter? Thanks in advance! Roel (the Netherlands)

**Comment by softins** [comment] 2024-04-18 10:46
Try going into **Audio MIDI Setup** and check the Zoom input device, particularly the level and the mute status.

**Comment by roelbakker123** [comment] 2024-04-18 16:05
Thank you very much for your reply. Unfortunately, it does not help. A
strange thing is that I do manage to make a connection with a borrowed
Focusrite, but not with the Zoom R24. Even more strange: the R24 does
connect with a DAW like Logic Pro. I can’t figure out if the problems are
evoked by Jamulus or by the R24 as an audio interface.
Kind regards, Roel

Op do 18 apr 2024 om 12:46 schreef Tony Mountifield <
***@***.***>

**Comment by softins** [comment] 2024-04-18 16:26
Hmm, sorry, I don't know what else to suggest. It sounds like you need to find someone local who would be knowledgeable in this area. If you are on Facebook, you could join the group **Jamulus (official group)** and ask there. There are a lot of Jamulus users in the Netherlands who are in that group, and you may find someone nearby.

It's possible there is some incompatibility in Jamulus, but that would be very hard to diagnose without the same hardware on a development machine.

Just out of interest, what version of macOS are you running?

**Comment by roelbakker123** [comment] 2024-04-18 17:01
Good suggestions, thanks!! I have two Macs, a brand new one with Sonoma and
an older one. It does not work on both!
Regards! Roel

Op do 18 apr 2024 om 18:27 schreef Tony Mountifield <
***@***.***>

**Comment by chrisrimple** [comment] 2024-04-18 17:09
Looking at the Zoom website, in the Support section, I found the manuals for the R24.  There is an Audio Interface manual.  On page 2 of that manual, it appears to say that the R24 only supports a sampling rate up to 44.1KHz.  Jamulus requires a sampling rate of 48KHz.

If you open the Audio MIDI Setup application on your Mac, then click on the Window menu and choose Show Devices (if that window is not already visible), then click on the Zoom R24 in the list on the left side, are you able to set the Input and Output sample rates on the right to 48KHz?  If you cannot, then the device will not work with Jamulus.

![Screen Shot 2024-04-18 at 10 06 20 AM](https://github.com/jamulussoftware/jamulus/assets/47258736/c057e17f-5d13-420c-a838-6cf9e6451f97)

**Comment by roelbakker123** [comment] 2024-04-18 17:35
This is genius, thank you very much!! I’ll let you know by tomorrow if it
works! Thanks a lot!!

Op do 18 apr 2024 om 19:09 schreef Chris Rimple ***@***.***>

**Comment by roelbakker123** [comment] 2024-04-18 20:45
Dear Chris, I have checked the manual and found that R24 as an interface
does support 48 KHz, but not the 'effects part' of the R24, that part only
supports 44.1 KHz. It is a huge pity, but your suggestion is not the
solution for my problem. Anyway, I have appreciated your efforts very much!
I will continue searching for a solution. Kind regards from the Netherlands!

Op do 18 apr 2024 om 19:09 schreef Chris Rimple ***@***.***>:

**Comment by chrisrimple** [comment] 2024-04-18 21:32
Another guess that may help...

Since your DAW "sees" the R24 and receives input from the microphone but Jamulus does not, check the Jamulus settings for Input Channel.  After you select Device = IN:R24/OUT:R24, Jamulus will probably default to Left Input = Channel 1 and Right Input = Channel 2.  But maybe you have the microphone plugged into Input 3 in the R24, which the DAW sees because it's "listening" to all inputs, while Jamulus does not because it's only "listening" to channels 1 and 2.

I use an audio interface with 4 inputs, and I have to set Jamulus to channels 3 and 4 for my microphone and keyboards.

**Comment by roelbakker123** [comment] 2024-04-19 06:28
I will try and let you know! I came to a same sort of conclusion this
night; it sounds logical! Thanks again for your efforts!!

Op do 18 apr 2024 om 23:33 schreef Chris Rimple ***@***.***>

**Comment by roelbakker123** [comment] 2024-04-19 17:28
Hello Chris, I am happy to tell you that your last suggestion works! I am
very happy and grateful! One last question however: when you start Jamulus,
but have not yet made a connection with any server, would it be able to see
your microphone (leds are peaking)? For with me I can only see that my
microphone works when I connect to a server. Is that how it should be?
Anyway, you have been of great help! Kind regards, Roel Bakker

Op do 18 apr 2024 om 23:33 schreef Chris Rimple ***@***.***>:

**Comment by chrisrimple** [comment] 2024-04-19 18:06
Great news that your microphone is now working with Jamulus.

Yes, you will only hear yourself (and see your microphone LEDs peaking) when you're connected to a server.  That's by design - musicians using Jamulus should only be listening to the sound returned from the server (including yourself) so that you can stay in sync with others.  If you join a server with other musicians but don't want to be heard while you test your equipment, click on the Mute Myself button - your sound will still be sent to the server, but will not be distributed to the other musicians on that server, and will only come back to you.

**Comment by roelbakker123** [comment] 2024-04-19 18:15
Thanks again, good to know! May I ask if you are mailing from the US, or
are you living in Europe as well?

Op vr 19 apr 2024 om 20:06 schreef Chris Rimple ***@***.***>

**Comment by chrisrimple** [comment] 2024-04-19 18:19
I'm in the US, but there are many Jamulus users in Europe.  You might look at these Facebook groups...

https://www.facebook.com/groups/619274602254947
https://www.facebook.com/groups/507047599870191

**Comment by softins** [comment] 2024-04-19 21:49
>  If you join a server with other musicians but don't want to be heard while you test your equipment, click on the Mute Myself button - your sound will still be sent to the server, but will not be distributed to the other musicians on that server, and will only come back to you.

Although it's not relevant to the issue at hand, I wanted to correct a detail here, having just checked the code to be sure.

There is nothing in the server that knows if a user has enabled **Mute Myself**. That option is processed entirely in the client. When enabled, the client sends silence to the server instead of the user's own audio. The user's audio is still stored in a buffer within the client, and it is then mixed locally with the audio received back from the server.

**Comment by chrisrimple** [comment] 2024-04-19 21:51
@softins Thanks for clarifying.  :)

**Comment by softins** [comment] 2024-04-19 21:52
> Hello Chris, I am happy to tell you that your last suggestion works! I am very happy and grateful!

That's great news, and I'm glad Chris was able to help you. (Thanks Chris!)

**Comment by ann0see** [comment] 2024-04-22 21:51
Closed as it seems to be resolved

**Closed** 2024-04-22 21:50 UTC
