### ISSUE TITLE
Update fr_FR app translation for 3.10.0

### ISSUE THREAD

**Issue by pljones** [jamulussoftware/jamulus#3123] opened 2023-07-30 10:59 UTC
Hi @jujudusud,
We are getting ready for the 3.10.0 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **fr_FR** by **2023-08-20**.

Please either [update the translations on Hosted Weblate](https://hosted.weblate.org/projects/jamulus/) or use Git:
- Update your fork from `jamulussoftware/jamulus` `main` and create a working branch
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2023-08-20

Suggested commit and PR message:
```
Update fr_FR app translation for 3.10.0

Fixes #3123
```

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/main/docs/TRANSLATING.md).

Thanks for contributing to Jamulus!

<a href="https://hosted.weblate.org/engage/jamulus/"><img src="https://hosted.weblate.org/widgets/jamulus/-/jamulus-app/multi-auto.svg" alt="Translation status" /></a>

**Comment by trebmuh** [comment] 2023-07-30 19:08
Hi @pljones and all.

There is something I don't understand in the process. Let's look at [this example](https://hosted.weblate.org/translate/jamulus/running-a-server/fr/?checksum=5200104d4a15c268). We can see in the history that it's has been translated 11 days ago, but yesterday something removed the translation. Then jujudusud had to reinstall the translation.

Is there something wrong in the translation process? Or is there anything I don't understand or that I'm misinterpreting?

**Comment by ann0see** [comment] 2023-07-31 18:05
Maybe the updated .ts files invalidated content?

**Comment by ann0see** [comment] 2023-07-31 18:09
(please close this issue if everything is up to date and in a releasable state)

**Comment by henkdegroot** [comment] 2023-07-31 19:07
@ann0see, not sure what you did 5 minutes ago...same thing now happened to the Dutch translation (for the website, not the app), same as the example posted by @trebmuh. At least it looks like your account is associated to that.

**Comment by ann0see** [comment] 2023-07-31 19:15
Yes. I know. The whole website had a conflict issue. I'm currently fixing all the languages.

**Comment by henkdegroot** [comment] 2023-07-31 19:18
@ann0see, it also change the app translation. Are you fixing all and should I stop updating?

**Comment by ann0see** [comment] 2023-07-31 19:19
I've fixed some languages for the app - but it's better if you fix your language.

**Comment by trebmuh** [comment] 2023-07-31 19:22
For what it worth, it happened [here](https://hosted.weblate.org/translate/jamulus/jamulus-app/fr/?checksum=2002b4274200dabf) and [there](https://hosted.weblate.org/translate/jamulus/installation-for-linux/fr/?q=is:untranslated#history) too.

I'm stopping translating for today and leaving you @ann0see to work on fixing things. And I'll keep translating again from tomorrow.

By the way, thanks for taking care about the quality of all the translation system and to react quickly at thing I'm reporting, it is highly appreciated from here.

**Comment by ann0see** [comment] 2023-07-31 19:23
The current thing was absolutely my fault. Sorry about that. I'm fixing the mess - I think the app is ok.

**Comment by henkdegroot** [comment] 2023-07-31 19:39
thank you for the effort!

**Comment by ann0see** [comment] 2023-07-31 19:40
@henkdegroot how much is broken in your translation? I *think* that French, German, Italian, Polish and Spanish should be ok

**Comment by henkdegroot** [comment] 2023-07-31 19:42
Already fixed the app and the website related only 2 files left. Will fix them now.

**Comment by ann0see** [comment] 2023-07-31 19:43
Ah great.

**Comment by pljones** [comment] 2023-08-01 19:27
@henkdegroot please comment / close when you're happy :)

**Comment by henkdegroot** [comment] 2023-08-01 21:07
fr_FR is not mine to close :) Just reported my issue here as it was the same for NL and noticed this being discussed.

I am sure @jujudusud will close once he confirmed the weblate update is correct.

**Comment by jujudusud** [comment] 2023-08-07 12:28
As everything seems to be going well on my side, I'm going to put an end to this issue.

**Comment by jujudusud** [comment] 2023-08-07 12:29
Thanks @trebmuh and all the team.

Closed as completed.

**Closed by jujudusud** 2023-08-07 12:29 UTC
Labels: translation

**Comment by trebmuh** [comment] 2023-08-08 15:56
I didn't review the app translation yet, only the manual so far.

**Comment by trebmuh** [comment] 2023-08-12 09:49
I've finished fixing the French translations strings for the app.
I've left a comment for @ann0see and @pljones : https://hosted.weblate.org/translate/jamulus/jamulus-app/fr/?&offset=25#comments

@pljones as I've been translating jamulus since the early covid time, I'd like to be pinged for translation next time. @jujudusud I'd have liked this issue not to be closed before I've review things. I guess those 2 sentences might sound slightly grumpy, and I guess they're just oversights, but the addition of those 2 things made me feel left out. So it's probably best to express it here.

**Comment by jujudusud** [comment] 2023-08-12 17:33
@trebmuh , I think you're doing a great job of saying what you feel and what you think. I understand your feeling of being sidelined, but I want to reassure you.
That's absolutely not the case. For being clumsy and making you feel that way, I apologize profusely.

@pljones , @ann0see , @ignotus666 : Is it possible to address the issues to trebmuh in addition to me?
If it's not possible, I'll let him know as soon as I receive an issue in the future.

**Comment by ann0see** [comment] 2023-08-12 21:03
Yes. Probably the create translation issues script needs to be updated (in the tools/ directory)

**Comment by jujudusud** [comment] 2023-08-12 22:43
please see #3146
