### ISSUE TITLE
Option to disable OPUS encoding on client

### ISSUE THREAD

**Issue by sthenos** [jamulussoftware/jamulus#516] opened 2020-08-12 01:09 UTC
Whilst those on low bandwidth internet connections probably need audio encoded for fast transmission of the audio data.  Many people have very good quality connections.    

It would be useful for those that do, to have an option to switch off opus encoding.  The server would auto-negotiate and would not encoding the buffer back to the client and the client wouldn't encode the buffer to the server.

**Comment by corrados** [comment] 2020-08-12 11:09
You would loose the packet loss concealment (PLC) included in OPUS. Have you tried to increase the OPUS coderate to get a better audio quality?
Another issue is that, e.g., my virtual server has a traffic limitation. Uncoded data would significantly increase the data traffic on the servers.

**Comment by corrados** [comment] 2020-08-12 15:27
Here is a link to the number which define the OPUS quality: https://github.com/corrados/jamulus/blob/master/src/client.h#L86
Just increase the numbers until you get the audio quality you would like to have.

**Comment by jerogee** [comment] 2020-08-15 17:20
@sthenos, just out of curiosity, why would it be useful for those who have very good connections? In other words, how (much) would "not encoding" buffers affect overall latency? If you are going to play around with the numbers, could you do some benchmarking? Really curious!!

**Comment by dyfer** [comment] 2020-09-09 19:17
I'd like to inquire about the latency associated with using OPUS. Based on [wikipedia](https://en.wikipedia.org/wiki/Opus_(audio_format)#cite_ref-testing_9-0) referencing [this PDF](https://www.ietf.org/proceedings/80/slides/codec-4.pdf), the low latency OPUS mode uses 5ms frames. Does that mean that because of encoding we induce at least 20ms latency, on top of network and audio interface latencies, as a result from client encoding + server decoding + server encoding + client decoding, each step taking 5ms? Do I theorize correctly that by using uncompressed audio at 128 sample buffer we could possibly cut this time in half, since (at 48k) 128 sample buffer is 2.6 ms long?

**Comment by bflamig** [comment] 2020-09-12 22:03
I'm no expert at this, but according to the source code for Jamulus, "OPUS additional delay at small frame sizes is half a frame size."

When using small network buffers and a 64 sample sound card setting, this means 64/2 = 32 samples, or 32 * 1000 / 48000 = 0.67 ms. That's how much is added to the delay total, according to the source code.

So the delay for the OPUS encoding/decoding is minimal. OPUS was designed for low-latency compression and it's a pretty good guess that's one of the reasons it is used in Jamulus.

**Comment by gilgongo** [comment] 2021-02-19 12:24
Hi - seeing as we've not had any resolution on this and it appears to be something possibly out of scope for Jamulus (HPSJam is out there too don't forget!) I'm closing this now to tidy up the Issues a bit. Feel free to discuss and create any actionable spec for a future work ticket as a [Discussion](https://github.com/jamulussoftware/jamulus/discussions) if you want of course.

**Closed by gilgongo** 2021-02-19 12:24 UTC
