### ISSUE TITLE
Redundant stereo signal sent to server on Mono-in/Stereo-out mode

### ISSUE THREAD

**Issue by diegodlh** [jamulussoftware/jamulus#531] opened 2020-08-20 00:01 UTC
In Mono-in/Stereo-out the client mixes a stereo input into a mono signal, as expected. However, the signal sent to the server seems to be stereo, with identical left and right channels.

This is what I've noticed:
- Audio stream rate is the same for Mono-in/Stereo-out than for Stereo mode.
- Network transfer rates (as measured with Linux's `iftop`) are the same for both modes. I expected Tx on the client side (and Rx on the server side) to be lower for Mono-in/Stereo-out mode.
- When server recording is enabled, the recording in Mono-in/Stereo-out mode is stereo, and both channels seem to be identical (redundant).

I'm using Jamulus 3.5.9git (a708a53cd0229c3b7fb0a667c5ad07264f167612)

**Comment by corrados** [comment] 2020-08-20 06:42
Yes, that's correct. The audio streams from/to the server are right now always symmetrical. The Mono-in/Stereo-out mode was not introduced to reduces network traffic but only to support, e.g., audio cards where you put your microphone on one channel and your instrument on the other channel. That was the intention.

**Comment by corrados** [comment] 2020-08-23 20:19
> In MS mode, users can apply reverb to only one of the two input channels, whereas in S mode users can (and have to) apply the same reverb to both channels.

Yes, correct. As I wrote, the idea was to support an instrument and a microphone for vocals. For that use case usually you want to have reverb on your microphone but not on your instrument. Do you see a need to apply the reverb on both channels?

> In MS mode users can set their input left/right balance as they wish and force it to the other musicians. In S mode, both channels are sent independently.

In MS mode you can adjust the level ratio between the instrument and microphone by using the Pan slider. So, e.g., you can increase/decrease the level of your instrument in comparison to your microphone. In stereo mode, the Pan acts like a normal Pan on an analog mixer. You can attenuate one channel in comparison to the other channel.

> From your reply, I understood that the fact that the audio stream from/to the server in MS mode is symmetrical is not a design decision, but rather something that could and should be changed if someone finds the time to do it. Right?

Yes, it could be changed. But I do not see a need for it. If the upstream rate of your internet connection does not allow a stereo stream to be used, then you can switch to mono mode. But usually the upstream rate of the client is not an issue. At the server side, you usually have a symmetric traffic limitation if you, e.g., use a virtual server. Then it does not matter if you have a redundant mono stream.

**Comment by diegodlh** [comment] 2020-08-25 15:36
Thank you Volker once again!

> Do you see a need to apply the reverb on both channels?

No. Just wanted to make sure I wasn't missing any difference between how MS and S modes operate.

> At the server side, you usually have a symmetric traffic limitation if you, e.g., use a virtual server. Then it does not matter if you have a redundant mono stream.

You are absolutely right here. Only thing I would say, just for the record (in case anyone wants to work on this in the future), is that this redundancy may impact:
- server storage, because recordings take up double space they should, and
- presumably server cpu usage too? I didn't test this thoroughly, but I would assume processing a stereo signal is more demanding than processing a mono signal, and minimizing cpu usage per client may be important in large rooms such as those needed by choirs.

Last, in reply to @gilgongo:
> The audio signal sent to the server is mono but the return signal is stereo.

This is exactly what I think might be misleading. But I understand it may be the easiest way to express it.

**Comment by corrados** [comment] 2020-10-07 15:30
> presumably server cpu usage too? I didn't test this thoroughly, but I would assume processing a stereo signal is more demanding than processing a mono signal, and minimizing cpu usage per client may be important in large rooms such as those needed by choirs.

That is the reason I kept this Issue open. Yes, recently there is a lot of work going into optimizing Jamulus for a large number of singers. Maybe sometime in the future it makes sense to optimize the mono-in/stereo-out mode so that it only transmits a mono signal which can be decoded quicker and with less CPU usage.

**Comment by ginjo** [comment] 2020-10-11 23:17
I see three main use cases that could warrant three (maybe 4) different mono-vs-stereo input modes. Each of these modes considers client input setup, client output (received from server), and recording output.

1. Client presents a stereo mixdown for input. This is the current stereo-in, and it works well for all three of the above mentioned considerations.

2. Client presents a dual or single mono channel and wants mixdown before sending just ONE upstream channel. This would follow the current mono-in functionality, but it would conserve upstream bandwidth (and server CPU?) by sending just one channel upstream. Recording output for this client would be a single mono track, reducing storage requirements. This scenario puts client's received mixdown at the low end of priority, while favoring resource conservation.

3. Client presents dual mono input and sends dual mono channels upstream. Mixdown is determined by each receiving client and performed on the server. Recording output is dual mono files, or single stereo file (but channels are NOT mixed, preserving the original dual mono split).

This third option would be a boon to recorded sessions (and post processing/mixdown), as it favors the mic/instrument type of setup and more granular recording output. And moving the dual-mono mixdown away from the client input and onto the server would allow receiving clients to set their own mix between the two mono input channels. This might require one more control on each receiving channel strip, but I don't think it would require more server resources beyond what stereo in/out requires.


Looking at this in terms of client interface, I imagine the following options and controls for audio input:

1. Stereo input. Exactly the same as it works now.

2. Single mono. Same as the current mono option but eliminates the redundant channel at all stages of the input chain. Recording output is single mono file.

3. Composite mono. same as current mono, including local pre-server mix, but eliminates redundant channel being sent upstream. Recording output is a single mono file.

4. Dual mono. No pre-server mixing, client channel strips have an extra control for the dual mono mix (or maybe an entire channel strip for each of the dual mono channels). Recording is dual mono in separate files or stereo files, but NOT mixed.


So that's my ultimate jamulus 😄
Thanks for the awesome software!

**Comment by AndyMcProducer** [comment] 2020-11-04 14:12
If any mono was just on left there'd be little data on right, would this reduce bandwidth?

**Comment by gilgongo** [comment] 2021-02-19 12:15
Hi all - this ticket is rather old, but I understand the issue is withe OPUS not Jamulus itself, so closing for now. If you want to talk about it further please open a [Discussion](https://github.com/jamulussoftware/jamulus/discussions). Thanks!

**Closed** 2021-02-19 12:17 UTC
Labels: improvement
