### ISSUE TITLE
Sticky text alignment in chat

### ISSUE THREAD

**Issue by passing** [jamulussoftware/jamulus#869] opened 2021-01-19 12:31 UTC
Jamulus version used: 3.6.2 on Windows 10

# Issue

I noticed the following issue in the chat:

When you set the welcome message on your server to something like this:
```
<center>hello</center>
```
all messages written in the chat window (including timestamp and name) will be centered after you have connected to that server.
That issue persists even if you connect to a different server and only restarting your Jamulus Client or deleting the chat history resets the text alignment

using `<div>` instead of `<center>` works in a similar way
```
<div style="text-align: center">hello</div>
<div style="text-align: right">hello</div>
```

The problem can also be triggered by sending a message to the chat in the client:
```
<center>hello</center>
```
or by just sending the opening html tag
```
<center>
```

# Workaround

As a workaround you can add a `<div>` to your welcome message that resets the alignment like this:
```
<center>hello</center><div style="text-align: left"/>
```

in the same way, you can reset the text alignment as a user by just sending this to the chat
```
<div style="text-align: left"/>
```

**Comment by dcorson-ticino-com** [comment] 2021-01-19 16:22
Other workaround, simply put a <br> at the end of the line.

**Comment by corrados** [comment] 2021-01-19 17:54
With `txvChatWindow->setAlignment ( Qt::AlignLeft );` I can force the chat dialog to be left aligned. This would look like this, using your example `<center>hello</center>` and some other text:
![grafik](https://user-images.githubusercontent.com/46655886/105073669-a3cae500-5a87-11eb-844a-288fb5df075c.png)
The problem is that existing server welcome messages would like different afterwards...

**Comment by passing** [comment] 2021-01-19 18:29
I think it would be nice to still support centered welcome messages.
Since adding a `<br>` seems to solve the issue, maybe that could be done automatically for every message entered?

**Comment by passing** [comment] 2021-01-20 19:20
found the following in the [Qt documentation](https://doc.qt.io/qt-5/qtextedit.html#introduction-and-concepts) of QTextEdit which gets inherited by QTextBrowser:

> QTextEdit works on paragraphs and characters. A paragraph is a formatted string which is word-wrapped to fit into the width of the widget. By default when reading plain text, one newline signifies a paragraph. A document consists of zero or more paragraphs. The words in the paragraph are aligned in accordance with the paragraph's alignment. Paragraphs are separated by hard line breaks

According to that it seems that all messages in a chat are added to the same paragraph right now. And by attaching a "hard line break" you could cause each message to be in it's own paragraph and so not take over the alignment of the previous message.
So I would expect that adding just a `\n` linebreak to every message (and welcome message) would be enough.

**Comment by corrados** [comment] 2021-01-21 16:25
Unfortunately, it does not work. I tried it with `txvChatWindow->append ( strChatText + "\n" );` but the "center" was not cleared.

**Comment by passing** [comment] 2021-01-23 15:28
then maybe adding `<br>` will help, at least that seems to help when adding it manually.

**Comment by corrados** [comment] 2021-01-24 19:21
> then maybe adding <br> will help, at least that seems to help when adding it manually.

That does not work for me. What I did was:
- connect to a Jamulus server
- send `<center>hello</center>`
- send any other normal text
- -> this normal text is centered which is not supposed to be
- send `<br>`
- send another normal text
- -> this other normal text is still centered

What are you doing differently?

**Comment by dcorson-ticino-com** [comment] 2021-01-24 23:59
<center>hello</center><br>  ->works
<center>hello</center>anything<br>   ->works

<center>hello</center>
anything<br>   ->doesn't work

The <br> needs to be on the same line apparently

**Comment by corrados** [comment] 2021-01-25 17:23
As in 3.6.2 (reference):
![grafik](https://user-images.githubusercontent.com/46655886/105740783-d0747600-5f39-11eb-8cbe-971b7e35287d.png)

Using `txvChatWindow->append ( strChatText + "<br>" );`:
![grafik](https://user-images.githubusercontent.com/46655886/105740960-09ace600-5f3a-11eb-832b-76fefb68a1d2.png)
The spaces between the text messages do not look nice in my opinion.

Alternative: Using `txvChatWindow->append ( strChatText + "<hr>" );`:
![grafik](https://user-images.githubusercontent.com/46655886/105741139-41b42900-5f3a-11eb-85d7-fb3256f9b7a8.png)
This also solves the "center" problem but I actually don't like that solution either...

**Comment by hoffie** [comment] 2021-01-25 17:42
Also note that there are even more formatting options which can leak, such as:
```My message which will turn anything afterwards red...<div style="background: red">```

![chat-background-leak](https://user-images.githubusercontent.com/762915/105740290-5a700f00-5f39-11eb-8847-7ef0f3eca8c6.png)

I played around with the code a little. My results so far:
- [`append()`](https://doc.qt.io/qt-5/qtextedit.html#append) behaves special in that it attempts to append a paragraph which resembles the previous formatting options.
- [`insertHtml()`](https://doc.qt.io/qt-5/qtextedit.html#insertHtml) permits more possibilities and I suspect one could try to reset all styling this way. Sounds a bit cumbersome...

Note: Neither appending `<br>` nor append `<hr>` solved this for me in cases with missing end tags (i.e. `<center>` without `</center>`). If it did, there may be ways (using CSS) to hide the extra space or line.

I will play around some more.

**Comment by houbsta** [comment] 2021-02-02 13:55
I would strip html from anything but the welcome messages, and just have link parsing only. Welcome messages should probably be automatically included with a <div> and </div>.

<center> and tags like it were deprecated in HTML5.

**Comment by passing** [comment] 2021-02-02 16:20
it would just be nice to still be able to share tabs in the chat (https://github.com/jamulussoftware/jamulus/issues/890#issuecomment-771754260)

**Comment by hoffie** [comment] 2021-02-17 10:02
@passing Could you open a new issue for that request? This issue and the referenced one are a bit cluttered by now... :)
@ann0see This issue could then be closed as it is basically fixed by #939.

**Comment by ann0see** [comment] 2021-02-17 10:34
Ok. I'll close it.

**Closed by ann0see** 2021-02-17 10:34 UTC
Labels: bug

**Comment by passing** [comment] 2021-02-18 23:08
> it would just be nice to still be able to share tabs in the chat ([#890 (comment)](https://github.com/jamulussoftware/jamulus/issues/890#issuecomment-771754260))

created #1020
