### ISSUE TITLE
'What's This" Delay LED Tooltip isn't entirely clear 

### ISSUE THREAD

**Issue by mulyaj** [jamulussoftware/jamulus#2290] opened 2022-01-26 20:46 UTC
When using "What's this" tooltip the Delay LED, the tooltip message doesn't quite answer the question of "What's this", outside of a vague statement.

https://github.com/jamulussoftware/jamulus/blob/f1022da9affeeb9aa7ee121b2f7533268d7ffac0/src/clientdlg.cpp#L207-L209

Solution:
I think it should be similar (or as technical) to the Jitter explanation just below it.

https://github.com/jamulussoftware/jamulus/blob/f1022da9affeeb9aa7ee121b2f7533268d7ffac0/src/clientdlg.cpp#L160-L162

**Comment by pljones** [comment] 2022-01-27 07:18
I don't think the suggestion helps - certainly the first sentence is unnecessary filler.  The user should be able to hear the effect, too, so the second sentence doesn't really add anything.  The existing text is just as good.

**Comment by gilgongo** [comment] 2022-01-27 20:54
The phrase "the Jamulus software" is a bit odd though.

**Comment by pljones** [comment] 2022-01-27 21:08
> The phrase "the Jamulus software" is a bit odd though.

Just "Jamulus" would be better, indeed.

**Comment by gilgongo** [comment] 2022-01-27 21:17
We could take this opportunity to sync up the website docs? They currently say, "The delay is too large for jamming" for the red LED, so maybe both could be similar to "If this indicator turns red, the delay is too large to play properly." ?

**Comment by mulyaj** [comment] 2022-01-27 21:31
>We could take this opportunity to sync up the website docs?

Yes, this was something I was going to suggest as well. The website's explanation is more concise.

**Comment by pljones** [comment] 2022-01-28 07:13
Jitter, not delay, is what makes jamming really impossible.  If you watch Worldjam, you'll see people playing together with very large delays.  You learn how to cope.  So, for the Delay LED, I'm not keen on an absolute decree.

**Comment by gilgongo** [comment] 2022-01-28 08:12
Interesting - so how about, "A red LED means your delay is large enough for you to need to play ahead of the beat."? On the website we might even add that maybe a 50ms delay is about the same as playing 18m away from somebody.

**Comment by pljones** [comment] 2022-01-28 16:41
The problem is _thinking_ about it 😃 .  If you try to think about it, it all falls apart in my experience - I can drum at 70ms latency (not ping), takes a little getting into ... but it's about listening to the server, as always and playing so it sounds on the beat.  And then not looking at your hands!! 😁 

So "A red LED means that playing won't sound naturally in time, you'll need to adjust your style" or something equally vague might be better.

But yeah, something explaining speed of sound in air on the website always helps.  18m is "a long way" in terms of normal performance space (think squeezed in behind a couple of chairs in the corner of a pub...).

**Comment by gilgongo** [comment] 2022-01-28 18:58
OK so what about,  "A red light means the you'll need to adjust your playing to compensate for the delay."  BTW I'm not sure "LED" is an immediately accessible term.

**Comment by pljones** [comment] 2022-01-28 22:20
Rather than "A red light means...", maybe just "When red, this means..."?  But that sounds pretty good to me.

**Comment by gilgongo** [comment] 2022-01-28 22:48
Until we have something like shapes as well as colours (eg green circle, yellow box, red triangle) I think it's probably a bit too hard to disambiguate the colour in the "What's this?" text.

**Comment by henkdegroot** [comment] 2022-01-30 18:17
> "What's this?" text.

BTW, the Tooltip text is not the same as the "What's this" text. The actual "what's this" text contains a lot more details.

> Until we have something like shapes

The Delay and Jitter LED do have accessibility indicators. A white cross in the red LED and a black circle in the yellow led.

**Comment by gilgongo** [comment] 2022-01-30 19:06
Yes, it's a bit hard to describe it but I suppose "When red with a cross mark..."

**Comment by henkdegroot** [comment] 2022-01-30 19:51
The tooltip also indicates you should read the what's this information for more detail. So not sure how much more detail you may need.

**Comment by ann0see** [comment] 2022-06-01 18:28
I agree that the text is not perfect. Why don't we sync what the website says – as suggested above?

**Comment by henkdegroot** [comment] 2022-06-01 19:33
Maybe we should just remove the "tooltip" for the Delay LED?

The jitter LED does not have a tooltip. Which seems to be a mistake in the code, in the section for the bufferLED, the almost the same text is set for the Tooltip however it is assigning it to the ledDelay again.

For both LED's, the What's This? text is "sort of" in sync with the web-site as the text is combined for connection stats and includes information for the ping time and delay. The What's This? text for the Jitter LED is a match with the web-site.

Actually looking more carefully at the code, I noticed there is a nicer/better text for the Delay LED "what's this" information, which gets overwritten later in the code with the connection stats text. Seems that is definitely something that should be fixed.

Current line 152 in Clientdlg.cpp:   ledDelay->setWhatsThis ( strLEDDelay );
Followed by line 207 in Clientdlg.cpp:     ledDelay->setWhatsThis ( strConnStats );

I can do a PR to cleanup these double assignments.

Once we agree on the "tooltip" I can include that update/change/remove as well. I would say that if the tooltip isn't there, then the "what's this" text will be used be the users. If we update the Delay LED tooltip, then we should also do a tooltip for the Jitter LED.

**Comment by henkdegroot** [comment] 2022-06-03 05:53
The PR current add's a tooltip for the Jitter LED. Left the existing tooltip for Delay LED in place.

**Closed** 2022-06-03 10:11 UTC
